In [1]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.cluster import  MiniBatchKMeans
import numpy as np
import pandas as pd
from __future__ import division

%autosave 0 

Autosave disabled


In [2]:


class HMM (object):
             def __init__(self,A,B,PI):
                 self.A=A
                 self.B=B
                 self.PI=PI   
def viterbi(obs,Modelo1,PI):
    
    delta=np.zeros((len(obs)+1,len(Modelo1.A)))
    phi=np.zeros((len(obs)+1,len(A)))+666
    path =np.zeros(len(obs)+1)
    T=len(obs)
    Modelo1.PI = PI
    delta[0,:]= Modelo1.PI * Modelo1.B[:,obs[0]]
    phi[0,:]=666
    for t in range(len(obs)):
        for j in range(delta.shape[1]):

            delta [t+1,j]=np.max(delta[t] * A[:,j]) * B[j,obs[t]]
            phi[t+1,j]= np.argmax(delta[t] * A[:,j])
    path[T]=int(np.argmax(delta[T,:]))
    for i in np.arange(T-1,0,-1):
        #print (i,phi[i+1,int(path[i+1])])
        path[i]=phi[i+1,int(path[i+1])]
    return(path)
def cuantizar_xy(xy, cc):
    xycuant=cc
    out=np.power(xycuant-xy,2).sum(axis=1).argmin()
    return out
    
def path_to_xy(path,ccxy):
    estimated= pd.DataFrame(path.astype(int).T)
    estimated.columns=[['Path_vit']]
    estimated['xcuant'] = estimated['Path_vit'].apply(lambda x: ccxy[x,0])
    estimated['ycuant'] = estimated['Path_vit'].apply(lambda x: ccxy[x,1])                                
    return (estimated)
def quantized(xyth,ccxyth):
    xythcuant=np.argmin(np.linalg.norm(xyth-ccxyth,axis=1))
    x,y=ccxyth[xythcuant,:2]
    return ((x,y),(xythcuant))



In [3]:
def Markov_A_2_grafo(A,ccxyth):
    dists=np.zeros(A.shape)
    for i in range(A.shape[0]):
        for j in range (A.shape[1]):
            if A[i,j]!=0 :
                dists[i,j]= np.linalg.norm(ccxyth[i]-ccxyth[j])    
    
    
    con = np.where(dists==0,np.inf,dists)
    graphe2=grafo(ccxyth,con)
    return graphe2


class node(object):
    def __init__(self,x,y):
        self.x=x
        self.y=y
        
        
class grafo (object):
             def __init__(self,nodos,conec):
                 self.nodos=nodos
                 self.conec=conec        

def dijkstra(nodoinicial,nodofinal,graphe):
    

    numnodos= len(graphe.nodos)
    con = graphe.conec
    D= np.ones(numnodos)*np.inf
    Prv= np.ones(numnodos)*np.inf
    V= np.zeros(numnodos)
    a = nodoinicial
    D[a]=0
    Prv[a]=0
    Prv[np.where(con[a]!=np.inf)]=a
    V[a]=1
    Dacc=D[a]
    ########
    D=np.minimum(D,con[a]+D[a])
    cont=0
    sucess=False
    while(sucess==False):
        a = np.argmin(D+np.where (V==1,np.inf, V))
        Dacc=D[a]
        Prv[np.where(D>(con[a]+Dacc) )]=a
        V[a]=1
        D=np.minimum(D,con[a]+Dacc)
        if (a== nodofinal):
            print("RUTA CALCULADA ")
            sucess=True
    rutainv=[]
    rutainv.append(nodofinal)
    while(rutainv[-1]!=nodoinicial):
        prv=Prv[int(rutainv[-1])]
        rutainv.append(prv)

    ruta=[]
    for n in reversed(rutainv):
        ruta.append(n)
    return(ruta)


In [4]:
only_nice=True
data=pd.read_csv('lecturasconodometria_nice.txt')
#data=data.iloc[:5000,:]

cols=['x','y','theta']
n_reads=data.shape[1]-3
n_reads
etiquetas=[]
for i in range (n_reads):
    etiquetas.append('R'+str(i))

        
for lab in cols:
    etiquetas.append(lab)


data.columns=etiquetas

if (only_nice!=True):
    print("NOT ONLY NICE")
    data2=pd.read_csv('lecturasconodometria.txt')
    data2.columns=etiquetas
    data3= pd.concat((data,data2))
    data=data3






####
#index = data[data.y<-1].index
#data=data.drop(index)
data.describe()



#####

xyth=data[['x','y','theta']]

lecs=data.iloc[:,0:n_reads]


data.describe()


R0            R1            R2            R3            R4  \
count  23877.000000  23877.000000  23877.000000  23877.000000  23877.000000   
mean       3.190143      3.189229      3.192182      3.194631      3.196241   
std        2.054171      2.065934      2.079633      2.096674      2.108123   
min        0.406166      0.404345      0.403152      0.401979      0.400827   
25%        1.628477      1.623511      1.618123      1.613172      1.609086   
50%        2.475462      2.465552      2.457282      2.447728      2.441308   
75%        4.466963      4.478095      4.493530      4.490005      4.502109   
max       12.282996     13.500000     12.294272     12.283157     13.500000   

                 R5            R6            R7            R8            R9  \
count  23877.000000  23877.000000  23877.000000  23877.000000  23877.000000   
mean       3.194398      3.190053      3.191011      3.194637      3.191882   
std        2.115277      2.120580      2.130139      2.148307      2.152622   
min        0.399097      0.397988      0.396898      0.395828      0.394177   
25%        1.604720      1.599621      1.595475      1.591735      1.588202   
50%        2.431842      2.422203      2.417037      2.407376      2.399940   
75%        4.506562      4.493653      4.496503      4.497544      4.491808   
max       12.294168     12.283052     12.272669     12.294942     12.283786   

           ...               R714          R715          R716          R717  \
count      ...       23877.000000  23877.000000  23877.000000  23877.000000   
mean       ...           3.117860      3.119370      3.123791      3.129620   
std        ...           1.990339      1.992633      1.993674      1.996469   
min        ...           0.300765      0.303960      0.302355      0.300858   
25%        ...           1.725976      1.729566      1.733253      1.736348   
50%        ...           2.466668      2.468918      2.475062      2.479255   
75%        ...           4.029264      4.023617      4.030480      4.034908   
max        ...          12.926135     12.968840     13.012271     12.941987   

               R718          R719          R720             x             y  \
count  23877.000000  23877.000000  23877.000000  23877.000000  23877.000000   
mean       3.137730      3.141248      3.148506     -0.172472      1.857350   
std        2.007682      2.006146      2.011755      1.986269      2.011609   
min        0.302843      0.304866      0.306926     -3.719565     -2.674327   
25%        1.741396      1.746020      1.750083     -1.872577      0.232127   
50%        2.482881      2.485480      2.492247     -0.041933      1.451492   
75%        4.032610      4.035877      4.043756      1.066181      3.692795   
max       12.873682     12.915410     12.957850      3.985533      5.514922   

              theta  
count  23877.000000  
mean       0.052452  
std        1.843144  
min       -3.141364  
25%       -1.437067  
50%       -0.004991  
75%        1.691020  
max        3.141482  

[8 rows x 724 columns]

In [264]:
get_new_ccs= True
if get_new_ccs:
    
    K_corpus=256
    N=100
    
    kmedias=MiniBatchKMeans(init='k-means++', n_clusters=K_corpus, batch_size=1000,
                      n_init=10, max_no_improvement=10, verbose=0)
    kmedias.fit(lecs)
    ccvk=kmedias.cluster_centers_
    mbk = MiniBatchKMeans(init='k-means++', n_clusters=N, batch_size=1000,
                      n_init=10, max_no_improvement=10, verbose=0)
    mbk.fit(xyth)
    ccxyth=mbk.cluster_centers_
else:
    ccxyth,ccvk=np.load('ccxyth.npy'),np.load('ccvk.npy')
    print("CUANTIZANDO SIN RECALCULAR CC")
aus=[]
auvks=[]
for i,lec in zip(xyth.values, lecs.values):
    _, au= quantized(i , ccxyth)
    aus.append(au)

    auvk= np.power(lec.T-ccvk,2).sum(axis=1,keepdims=True).argmax()
    auvks.append(auvk)
print(i ,au)
data['Y']=aus
data['Vk']=auvks
obs,est= data['Vk'].values,data['Y'].values
data['Y'].describe()   

/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:1279: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.p

/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:1328: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, self.batch_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:1328: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, self.batch_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:1328: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, self.batch_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:1328: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, self.batch_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:1328: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, self.batch_size)
/usr/lib/python2.7/dist-p

/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py

(array([-3.05064563,  2.46898844, -1.66027334]), 26)


count    23877.000000
mean        46.395318
std         28.087897
min          0.000000
25%         21.000000
50%         47.000000
75%         69.000000
max         99.000000
Name: Y, dtype: float64

In [265]:
####BAUM WELCH APPROX###############???!?!?!


N=est.max()+1 
K_corpus= obs.max()+1
TRANS=np.zeros((N,N))
for i in range (N):
    fromTO=[]


    indices=np.asarray(np.where(est==i)).ravel()
   

    for indice in indices:

        if (int(indice)==len(est)-1):
            
            indice=indice-1

        fromTO.append(est[indice+1])
    fromTO.append(0)
    fromTO.append(N-1)
    aux=np.asarray(np.bincount(fromTO    ))
    aux[0]=aux[0]-1
    aux[N-1]=aux[N-1]-1
    
    TRANS[i,:]=aux
TRANS=TRANS/TRANS.sum(axis=1)
#####################################3
EMIS= np.zeros((N,K_corpus))
for Vk in range (K_corpus):

    indices=np.asarray(np.where(obs==Vk)).ravel()
    estconvk= est[indices]

    numestenvk=np.bincount(estconvk)
    if (N-len(numestenvk)>0):
        numestenvk=np.append(numestenvk, np.zeros(N-len(numestenvk)))
    EMIS[:,Vk]=(numestenvk/np.bincount(est))

A,B=TRANS,EMIS
PI=np.ones(N)/N
Modelo1=HMM(A,B,PI)
Modelo2= HMM(A,B,PI)
Modelo2.B=B+.0000001
Modelo2.A=A+.0000001





A.shape , EMIS

((100, 100),
 array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.02075472],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]]))

In [266]:
def forw_alg(o_k,Modelo):
    PI=Modelo.PI
    K= len(o_k)   #Secuencia Observaciones
    N= len(Modelo.A)  #número de estados
    alpha=np.zeros((N,K))
    alpha[:,0]= PI
    
    for k in range(1,K):
        for j in range (N):
            alpha_k= alpha[:,k-1]
            a= Modelo.A[:,j]
            b= Modelo.B[j,o_k[k]]
            alpha[j,k]=b*np.dot(alpha_k,a)
        #norm=np.linalg.norm(alpha[:,k])
        norm=np.sum(alpha[:,k])
        #alpha[:,k]/= norm
            
                #alpha[k,i]=  np.sum( alpha[:,i-1]*Modelo.A[i,:] *   Modelo.B[:,o_k[k]] )
    
    
    

    
    
    
    
    
    return alpha
def  backw_alg(o_k,Modelo):
    PI=Modelo.PI
    K= len(o_k)   #Secuencia Observaciones
    N= len(Modelo.A)  #número de estados
    beta=np.zeros((N,K))
    beta[:,-1]=1
    
    for t in range(K-1,-1,-1):
        for i in range(N):
            
            beta_t1=beta[:,t+1]
            a= Modelo.A[i,:]
            b= Modelo.B[i,o_k[t]]
            beta[i,t]= b*np.dot(a,beta_t1)
       
        
            

    
    
    
    return beta
    

In [267]:
def forw_alg_norm(o_k,Modelo):
    #MATRIX NOTATION
    PI=Modelo.PI
    K= len(o_k)   #Secuencia Observaciones
    N= len(Modelo.A)  #número de estados
    alpha=np.zeros((N,K))
    c_k= np.zeros(K)
    alpha[:,0]= PI
    c_k[0]=1
    for k in range(1,K):
        alpha_k= alpha[:,k-1]
        a= Modelo.A[:,:]
        b= Modelo.B[:,o_k[k]]
        alpha[:,k]=(b*np.dot(alpha_k,a))* c_k[k-1]
        c_k[k]=1/alpha[:,k].sum()
    return alpha #,c_k
def  backw_alg(o_k,Modelo):
    #MATRIX NOTATION

    PI=Modelo.PI
    K= len(o_k)   #Secuencia Observaciones
    N= len(Modelo.A)  #número de estados
    beta=np.zeros((N,K))
    beta[:,-1]=1
    for t in range(K-2,-1,-1):
        beta_t1=beta[:,t+1]
        beta_t1
        a= Modelo.A[:,:]
        b= Modelo.B[:,o_k[t]]
        beta[:,t]= b*np.dot(a,beta_t1)
    return beta
    

In [268]:
#CALL BAUM WELCH
A,B

(array([[0.98913043, 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.98490566, 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.98989899, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.98830409, 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.984375  ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.98642534]]),
 array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.02075472],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0. 

In [269]:
o_k= obs[:30]
alpha,beta=forw_alg(o_k,Modelo1),backw_alg(o_k,Modelo1)

In [270]:
alpha.shape,beta.shape


((100, 30), (100, 30))

PR(O|Modelo) =  P  ; likelihood Lo(M)

In [271]:
T=len(o_k)
t=len(o_k)-1
P= alpha[:,t].sum()
P

2.9464656478631915e-23

gamma_ij=E{ transitions from state i to j conditioned to O}

In [272]:
gamma=np.zeros((N,N,T))
for t in range(T-1):
    for j in range(N):
        for i in range(N):
            a=Modelo1.A[i,j]
            b=Modelo1.B[j,o_k[t]]
            gamma[i,j,t]=alpha[i,t]*a*b*beta[i,t+1]
gamma=np.sum(gamma,axis=2)/P
gamma

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 7.48591643, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

gamma_i=E{Num of trans out of gamma_i out of ith state given O} = SUM j gamma_ij

In [273]:
gamma=np.sum(alpha*beta ,axis=1)/P
gamma

array([0.00000000e+00, 8.38606415e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       3.61164226e-06, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 2.08708963e-10, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 4.73287374e+01, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 8.47606867e-03, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 8.77773792e-04, 3.41690144e-02, 6.53525708e-15,
       0.00000000e+00, 5.33681163e-06, 0.00000000e+00, 1.07443823e-10,
       0.00000000e+00, 2.39170363e-05, 1.45073470e-09, 0.00000000e+00,
      

In [274]:
A

array([[0.98913043, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.98490566, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.98989899, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.98830409, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.984375  ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.98642534]])

In [275]:
lam=.5
eta=.5
W,V=np.zeros(A.shape),np.zeros(B.shape)
DW,DV=np.zeros(A.shape),np.zeros(B.shape)

In [276]:
A_gd=np.exp(lam*W)
for i in range(N):
    aux=A_gd[i,:].sum()
    A_gd[i,:]=A_gd[i,:]/aux


B_gd= np.exp(lam*V)
for i in range(N):
    aux=B_gd[i,:].sum()
    B_gd[i,:]=B_gd[i,:]/aux


A_gd , B_gd

(array([[0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01],
        [0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01],
        [0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01],
        ...,
        [0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01],
        [0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01],
        [0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01]]),
 array([[0.00392157, 0.00392157, 0.00392157, ..., 0.00392157, 0.00392157,
         0.00392157],
        [0.00392157, 0.00392157, 0.00392157, ..., 0.00392157, 0.00392157,
         0.00392157],
        [0.00392157, 0.00392157, 0.00392157, ..., 0.00392157, 0.00392157,
         0.00392157],
        ...,
        [0.00392157, 0.00392157, 0.00392157, ..., 0.00392157, 0.00392157,
         0.00392157],
        [0.00392157, 0.00392157, 0.00392157, ..., 0.00392157, 0.00392157,
         0.00392157],
        [0.00392157, 0.00392157, 0.00392157, ..., 0.00392157, 0.00392157,
         0.00392157]]))

In [277]:
Modelo_gd=HMM(A_gd,B_gd,PI)

In [278]:
o_k= obs[60:90]
alpha,beta=forw_alg(o_k,Modelo_gd),backw_alg(o_k,Modelo_gd)
LoM = alpha[:,-1].sum()

In [279]:
P=LoM
P

1.623060719929518e-70

In [280]:
gamma=np.zeros((N,N,T))
for t in range(T-1):
    for j in range(N):
        for i in range(N):
            a=Modelo1.A[i,j]
            b=Modelo1.B[j,o_k[t]]
            gamma[i,j,t]=alpha[i,t]*a*b*beta[i,t+1]
gamma=np.sum(gamma,axis=2)/P
gamma

array([[0.24674504, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.86691154, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 2.52017544, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [281]:
n_ij_o, n_i_o=gamma , gamma.sum(axis=1)

In [282]:
for i in range (N):
    for j in range (N):
         DW[i,j]=  (eta)* (  n_ij_o[i,j] -(n_i_o[i]* A_gd[i,j]))

In [283]:
DW

array([[ 1.22138794e-01, -1.23372519e-03, -1.23372519e-03, ...,
        -1.23372519e-03, -1.23372519e-03, -1.23372519e-03],
       [-2.87864303e-04, -2.87864303e-04, -2.87864303e-04, ...,
        -2.87864303e-04, -2.87864303e-04, -2.87864303e-04],
       [-4.33455770e-03, -4.33455770e-03,  4.29121212e-01, ...,
        -4.33455770e-03, -4.33455770e-03, -4.33455770e-03],
       ...,
       [-1.26174481e-02, -1.26174481e-02, -1.26174481e-02, ...,
         1.24747027e+00, -1.26174481e-02, -1.26174481e-02],
       [-1.36000000e-05, -1.36000000e-05, -1.36000000e-05, ...,
        -1.36000000e-05, -1.36000000e-05, -1.36000000e-05],
       [-2.92699725e-05, -2.92699725e-05, -2.92699725e-05, ...,
        -2.92699725e-05, -2.92699725e-05, -2.92699725e-05]])

In [284]:
W=W + DW
W

array([[ 1.22138794e-01, -1.23372519e-03, -1.23372519e-03, ...,
        -1.23372519e-03, -1.23372519e-03, -1.23372519e-03],
       [-2.87864303e-04, -2.87864303e-04, -2.87864303e-04, ...,
        -2.87864303e-04, -2.87864303e-04, -2.87864303e-04],
       [-4.33455770e-03, -4.33455770e-03,  4.29121212e-01, ...,
        -4.33455770e-03, -4.33455770e-03, -4.33455770e-03],
       ...,
       [-1.26174481e-02, -1.26174481e-02, -1.26174481e-02, ...,
         1.24747027e+00, -1.26174481e-02, -1.26174481e-02],
       [-1.36000000e-05, -1.36000000e-05, -1.36000000e-05, ...,
        -1.36000000e-05, -1.36000000e-05, -1.36000000e-05],
       [-2.92699725e-05, -2.92699725e-05, -2.92699725e-05, ...,
        -2.92699725e-05, -2.92699725e-05, -2.92699725e-05]])

In [285]:
lam=.5
eta=1.5

W,V=np.zeros(A.shape),np.zeros(B.shape)
DW,DV=np.zeros(A.shape),np.zeros(B.shape)

for k in range((int)(len(obs)/30)):
    o_k=obs[30*k:30*k+30]
    A_gd=np.exp(lam*W)
    for i in range(N):
        aux=A_gd[i,:].sum()
        A_gd[i,:]=A_gd[i,:]/aux
    B_gd= np.exp(lam*V)
    for i in range(N):
        aux=B_gd[i,:].sum()
        B_gd[i,:]=B_gd[i,:]/aux
    Modelo_gd=HMM(A_gd,B_gd,PI)
    alpha,beta = forw_alg(o_k,Modelo_gd), backw_alg(o_k,Modelo_gd)
    P = alpha[:,-1].sum()
    gamma=np.zeros((N,N,T))
    for t in range(T-1):
        for j in range(N):
            for i in range(N):
                a=Modelo1.A[i,j]
                b=Modelo1.B[j,o_k[t]]
                gamma[i,j,t]=alpha[i,t]*a*b*beta[i,t+1]
    gamma=np.sum(gamma,axis=2)/P
    n_ij_o, n_i_o=gamma , gamma.sum(axis=1)
    for i in range (N):
        for j in range (N):
             DW[i,j]=  (eta)* (  n_ij_o[i,j] -(n_i_o[i]* A_gd[i,j]))
    W=W + DW
    print(DW)

                
    
    
    
    

    

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.74893150e-01  1.70194691e+01 -1.74893150e-01 ... -1.74893150e-01
  -1.74893150e-01 -1.74893150e-01]
 [-4.71837179e-04 -4.71837179e-04 -4.71837179e-04 ... -4.71837179e-04
  -4.71837179e-04 -4.71837179e-04]
 ...
 [-1.58376896e-05 -1.58376896e-05 -1.58376896e-05 ... -1.58376896e-05
  -1.58376896e-05 -1.58376896e-05]
 [-2.94666667e-04 -2.94666667e-04 -2.94666667e-04 ... -2.94666667e-04
  -2.94666667e-04 -2.94666667e-04]
 [-8.61505495e-02 -8.61505495e-02 -8.61505495e-02 ... -8.61505495e-02
  -8.61505495e-02  8.51851356e+00]]
[[ 5.74365229e-02 -5.80166898e-04 -5.80166898e-04 ... -5.80166898e-04
  -5.80166898e-04 -5.80166898e-04]
 [-4.36284422e-04 -9.92475966e-01 -4.36284422e-04 ... -4.36284422e-04
  -4.36284422e-04 -4.36284422e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-5.92621410e-03 -5.92621410e-03 -5.9262141

[[ 3.11631304e+00 -3.14779095e-02 -3.14779095e-02 ... -3.14779095e-02
  -3.14779095e-02 -3.14779095e-02]
 [-6.16290182e-05  6.55611171e-03 -6.16290182e-05 ... -6.16290182e-05
  -6.16290182e-05 -6.16290182e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-2.07114844e-03 -2.07114844e-03 -2.07114844e-03 ...  2.03393195e-01
  -2.07114844e-03 -2.07114844e-03]
 [-2.01534830e-02 -2.01534830e-02 -2.01534830e-02 ... -2.01534830e-02
   1.99194534e+00 -2.01534830e-02]
 [-3.37902071e-05 -3.37902071e-05 -3.37902071e-05 ... -3.37902071e-05
  -3.37902071e-05 -4.31095362e-01]]
[[ 2.85236987e+00 -2.88118168e-02 -2.88118168e-02 ... -2.88118168e-02
  -2.88118168e-02 -2.88118168e-02]
 [-2.82003936e-04 -1.10077107e-01 -2.82003936e-04 ... -2.82003936e-04
  -2.82003936e-04 -2.82003936e-04]
 [-1.12424869e-07 -1.12424869e-07 -6.87997305e-03 ... -1.12424869e-07
  -1.12424869e-07 -1.12424869e-07]
 ...
 [-1.92070689e-03 -1.92070689e-03 -1.9207068

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [-0.00014157  0.01536614 -0.00014157 ... -0.00014157 -0.00014157
  -0.00014157]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.76190356e-04  2.44606890e-02 -2.76190356e-04 ... -2.76190356e-04
  -2.76190356e-04 -2.76190356e-04]
 [-3.62410829e-09 -3.62410

[[-3.89991558e-02 -2.20117967e-03 -2.20117967e-03 ... -2.20117967e-03
  -2.20117967e-03 -2.20117967e-03]
 [-5.48935093e-05 -6.52306551e-01 -5.48935093e-05 ... -5.48935093e-05
  -5.48935093e-05 -5.48935093e-05]
 [-5.07099858e-04 -5.07099858e-04  5.10024014e-02 ... -5.07099858e-04
  -5.07099858e-04 -5.07099858e-04]
 ...
 [-8.05657466e-05 -8.05657466e-05 -8.05657466e-05 ... -1.92141459e-03
  -8.05657466e-05 -8.05657466e-05]
 [-1.16681252e-03 -1.16681252e-03 -1.16681252e-03 ... -1.16681252e-03
   1.14691930e-01 -1.16681252e-03]
 [-3.55239269e-06 -3.55239269e-06 -3.55239269e-06 ... -3.55239269e-06
  -3.55239269e-06 -4.77447549e-02]]
[[-2.07781039e-02 -1.41034418e-03 -1.41034418e-03 ... -1.41034418e-03
  -1.41034418e-03 -1.41034418e-03]
 [-7.47049968e-05 -6.40686758e-01 -7.47049968e-05 ... -7.47049968e-05
  -7.47049968e-05 -7.47049968e-05]
 [-4.92976730e-04 -4.92976730e-04  4.95814370e-02 ... -4.92976730e-04
  -4.92976730e-04 -4.92976730e-04]
 ...
 [-4.40039222e-05 -4.40039222e-05 -4.4003922

[[ 4.71751677e-01 -8.42522317e-03 -8.42522317e-03 ... -8.42522317e-03
  -8.42522317e-03 -8.42522317e-03]
 [-3.48883641e-05 -1.82646836e-02 -3.48883641e-05 ... -3.48883641e-05
  -3.48883641e-05 -3.48883641e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-2.58881188e-04 -2.58881188e-04 -2.58881188e-04 ...  1.63271360e-02
  -2.58881188e-04 -2.58881188e-04]
 [-2.27851803e-03 -2.27851803e-03 -2.27851803e-03 ... -2.27851803e-03
   1.93407394e-01 -2.27851803e-03]
 [-2.06623369e-05 -2.06623369e-05 -2.06623369e-05 ... -2.06623369e-05
  -2.06623369e-05 -2.64868148e-01]]
[[ 2.95080781e-01 -2.32699596e-03 -2.32699596e-03 ... -2.32699596e-03
  -2.32699596e-03 -2.32699596e-03]
 [-8.84715051e-05 -6.99977322e-02 -8.84715051e-05 ... -8.84715051e-05
  -8.84715051e-05 -8.84715051e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-2.76975048e-03 -2.76975048e-03 -2.7697504

[[ 4.24011088e-01 -2.33549017e-03 -2.33549017e-03 ... -2.33549017e-03
  -2.33549017e-03 -2.33549017e-03]
 [-2.89754818e-05 -7.50004488e-03 -2.89754818e-05 ... -2.89754818e-05
  -2.89754818e-05 -2.89754818e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.82398178e-04 -1.82398178e-04 -1.82398178e-04 ...  7.22176122e-03
  -1.82398178e-04 -1.82398178e-04]
 [-5.96285789e-04 -5.96285789e-04 -5.96285789e-04 ... -5.96285789e-04
   2.75690091e-02 -5.96285789e-04]
 [-3.13766675e-05 -3.13766675e-05 -3.13766675e-05 ... -3.13766675e-05
  -3.13766675e-05 -1.32956592e-01]]
[[ 3.30560042e-01 -1.13856521e-03 -1.13856521e-03 ... -1.13856521e-03
  -1.13856521e-03 -1.13856521e-03]
 [-2.68992359e-05  3.80450515e-03 -2.68992359e-05 ... -2.68992359e-05
  -2.68992359e-05 -2.68992359e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-8.81729402e-04 -8.81729402e-04 -8.8172940

[[ 1.42221136e-01 -5.79652935e-04 -5.79652935e-04 ... -5.79652935e-04
  -5.79652935e-04 -5.79652935e-04]
 [-2.81510741e-05 -8.07907073e-02 -2.81510741e-05 ... -2.81510741e-05
  -2.81510741e-05 -2.81510741e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.64838529e-03 -1.64838529e-03 -1.64838529e-03 ...  1.63290978e-01
  -1.64838529e-03 -1.64838529e-03]
 [-1.68611560e-04 -1.68611560e-04 -1.68611560e-04 ... -1.68611560e-04
  -1.33982002e-02 -1.68611560e-04]
 [-1.66114259e-05 -1.66114259e-05 -1.66114259e-05 ... -1.66114259e-05
  -1.66114259e-05 -5.67647264e-02]]
[[ 3.22983223e-01 -1.35006176e-03 -1.35006176e-03 ... -1.35006176e-03
  -1.35006176e-03 -1.35006176e-03]
 [-4.82013230e-05  1.97888401e-03 -4.82013230e-05 ... -4.82013230e-05
  -4.82013230e-05 -4.82013230e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-9.36094957e-04 -9.36094957e-04 -9.3609495

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.77043793e-06 -2.61808003e-02 -4.77043793e-06 ... -4.77043793e-06
  -4.77043793e-06 -4.77043793e-06]
 [-3.60791989e-07 -3.60791989e-07 -1.68035995e-02 ... -3.60791989e-07
  -3.60791989e-07 -3.60791989e-07]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-9.32423498e-05 -9.32423498e-05 -9.32423498e-05 ... -9.32423498e-05
  -4.18780276e-02 -9.32423498e-05]
 [-3.58108083e-06 -3.58108083e-06 -3.58108083e-06 ... -3.58108083e-06
  -3.58108083e-06 -9.41067388e-03]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-6.26651110e-05 -3.39442666e-01 -6.26651110e-05 ... -6.26651110e-05
  -6.26651110e-05 -6.26651110e-05]
 [-3.62384112e-04 -3.62384112e-04  3.17034809e-02 ... -3.62384112e-04
  -3.62384112e-04 -3.62384112e-04]
 ...
 [-6.15657377e-06 -6.15657377e-06 -6.1565737

[[ 8.97963464e-01 -1.78244477e-03 -1.78244477e-03 ... -1.78244477e-03
  -1.78244477e-03 -1.78244477e-03]
 [-3.93125997e-05  5.66441547e-03 -3.93125997e-05 ... -3.93125997e-05
  -3.93125997e-05 -3.93125997e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-9.38003256e-04 -9.38003256e-04 -9.38003256e-04 ...  9.16030214e-02
  -9.38003256e-04 -9.38003256e-04]
 [-4.60745282e-04 -4.60745282e-04 -4.60745282e-04 ... -4.60745282e-04
  -7.13653110e-03 -4.60745282e-04]
 [-2.00755875e-05 -2.00755875e-05 -2.00755875e-05 ... -2.00755875e-05
  -2.00755875e-05 -2.34636308e-01]]
[[ 5.04936742e-01 -1.32566909e-03 -1.32566909e-03 ... -1.32566909e-03
  -1.32566909e-03 -1.32566909e-03]
 [-2.11156071e-04  3.04175228e-02 -2.11156071e-04 ... -2.11156071e-04
  -2.11156071e-04 -2.11156071e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.67344909e-03 -1.67344909e-03 -1.6734490

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-8.22831788e-05 -5.11936922e-01 -8.22831788e-05 ... -8.22831788e-05
  -8.22831788e-05 -8.22831788e-05]
 [-5.90907452e-04 -5.90907452e-04  6.04293945e-02 ... -5.90907452e-04
  -5.90907452e-04 -5.90907452e-04]
 ...
 [-3.20581534e-05 -3.20581534e-05 -3.20581534e-05 ... -4.16174733e-03
  -3.20581534e-05 -3.20581534e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.81314763e-03 -1.32665386e-02 -1.81314763e-03 ... -1.81314763e-03
  -1.81314763e-03 -1.81314763e-03]
 [-3.58353653e-04 -3.58353653e-04 -2.02999131e-02 ... -3.58353653e-04
  -3.58353653e-04 -3.58353653e-04]
 ...
 [-2.96341535e-05 -2.96341535e-05 -2.9634153

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.54629050e-05 -2.34808783e-01 -1.54629050e-05 ... -1.54629050e-05
  -1.54629050e-05 -1.54629050e-05]
 [-2.70840927e-04 -2.70840927e-04  1.92130522e-02 ... -2.70840927e-04
  -2.70840927e-04 -2.70840927e-04]
 ...
 [-2.13290863e-06 -2.13290863e-06 -2.13290863e-06 ... -3.70557382e-04
  -2.13290863e-06 -2.13290863e-06]
 [-1.00759400e-04 -1.00759400e-04 -1.00759400e-04 ... -1.00759400e-04
  -1.49210747e-02 -1.00759400e-04]
 [-6.06873492e-07 -6.06873492e-07 -6.06873492e-07 ... -6.06873492e-07
  -6.06873492e-07 -1.61426474e-02]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.33893234e-05 -6.40388828e-01 -4.33893234e-05 ... -4.33893234e-05
  -4.33893234e-05 -4.33893234e-05]
 [-7.95220354e-04 -7.95220354e-04  8.33210057e-02 ... -7.95220354e-04
  -7.95220354e-04 -7.95220354e-04]
 ...
 [-3.06428999e-05 -3.06428999e-05 -3.0642899

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.32672424e-08 -1.45523617e-04 -1.32672424e-08 ... -1.32672424e-08
  -1.32672424e-08 -1.32672424e-08]
 [-6.16060746e-08 -6.16060746e-08 -1.76970007e-03 ... -6.16060746e-08
  -6.16060746e-08 -6.16060746e-08]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-6.55211161e-07 -6.55211161e-07 -6.55211161e-07 ... -6.55211161e-07
  -5.80689509e-02 -6.55211161e-07]
 [-4.50828180e-08 -4.50828180e-08 -4.50828180e-08 ... -4.50828180e-08
  -4.50828180e-08 -1.38017782e-03]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[-3.37145730e-01 -9.14885305e-04 -9.14885305e-04 ... -9.14885305e-04
  -9.14885305e-04 -9.14885305e-04]
 [-3.76132207e-06 -3.58961121e-02 -3.76132207e-06 ... -3.76132207e-06
  -3.76132207e-06 -3.76132207e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-2.64472239e-05 -2.64472239e-05 -2.64472239e-05 ... -4.99583341e-03
  -2.64472239e-05 -2.64472239e-05]
 [-8.20222962e-04 -8.20222962e-04 -8.20222962e-04 ... -8.20222962e-04
   7.79677417e-02 -8.20222962e-04]
 [-9.75461037e-06 -9.75461037e-06 -9.75461037e-06 ... -9.75461037e-06
  -9.75461037e-06 -2.15956423e-01]]
[[-3.39674540e-02 -4.80278756e-04 -4.80278756e-04 ... -4.80278756e-04
  -4.80278756e-04 -4.80278756e-04]
 [-1.72458095e-06 -1.61657757e-02 -1.72458095e-06 ... -1.72458095e-06
  -1.72458095e-06 -1.72458095e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-5.88345727e-05 -5.88345727e-05 -5.8834572

[[ 1.43573230e-01 -1.90722103e-04 -1.90722103e-04 ... -1.90722103e-04
  -1.90722103e-04 -1.90722103e-04]
 [-3.68759017e-03  1.27068748e+00 -3.68759017e-03 ... -3.68759017e-03
  -3.68759017e-03 -3.68759017e-03]
 [-1.79775995e-04 -1.79775995e-04 -7.25500309e-02 ... -1.79775995e-04
  -1.79775995e-04 -1.79775995e-04]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-6.63731106e-05 -6.63731106e-05 -6.63731106e-05 ... -6.63731106e-05
  -3.35030510e-02 -6.63731106e-05]
 [-1.88072950e-03 -1.88072950e-03 -1.88072950e-03 ... -1.88072950e-03
  -1.88072950e-03  1.45592922e-01]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.73618649e-04  3.70694156e-02 -4.73618649e-04 ... -4.73618649e-04
  -4.73618649e-04 -4.73618649e-04]
 [-1.40631623e-07 -1.40631623e-07 -4.43496980e-03 ... -1.40631623e-07
  -1.40631623e-07 -1.40631623e-07]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.65160941e-08 -2.65160941e-08 -8.70243210e-04 ... -2.65160941e-08
  -2.65160941e-08 -2.65160941e-08]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-6.28227437e-07 -6.28227437e-07 -6.28227437e-07 ... -6.28227437e-07
  -4.37530042e-02 -6.28227437e-07]
 [-3.26628215e-05 -3.26628215e-05 -3.26628215e-05 ... -3.26628215e-05
  -3.26628215e-05  5.47628685e-03]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[-5.54788618e-01 -8.97735854e-04 -8.97735854e-04 ... -8.97735854e-04
  -8.97735854e-04 -8.97735854e-04]
 [-4.59152380e-06 -2.38466175e-02 -4.59152380e-06 ... -4.59152380e-06
  -4.59152380e-06 -4.59152380e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-2.40424334e-05 -2.40424334e-05 -2.40424334e-05 ... -1.37373790e-01
  -2.40424334e-05 -2.40424334e-05]
 [-1.20734363e-03 -1.20734363e-03 -1.20734363e-03 ... -1.20734363e-03
   1.18885152e-01 -1.20734363e-03]
 [-1.61096927e-05 -1.61096927e-05 -1.61096927e-05 ... -1.61096927e-05
  -1.61096927e-05 -2.00606127e-01]]
[[-8.13921616e-02 -1.02487645e-03 -1.02487645e-03 ... -1.02487645e-03
  -1.02487645e-03 -1.02487645e-03]
 [-4.59365415e-06 -2.35749624e-02 -4.59365415e-06 ... -4.59365415e-06
  -4.59365415e-06 -4.59365415e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-2.53586320e-05 -2.53586320e-05 -2.5358632

[[ 5.48264959e-03 -7.34567215e-06 -7.34567215e-06 ... -7.34567215e-06
  -7.34567215e-06 -7.34567215e-06]
 [-3.14428843e-06 -2.59791566e-02 -3.14428843e-06 ... -3.14428843e-06
  -3.14428843e-06 -3.14428843e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-6.16538253e-03 -6.16538253e-03 -6.16538253e-03 ...  6.18820373e-01
  -6.16538253e-03 -6.16538253e-03]
 [-8.72224482e-08 -8.72224482e-08 -8.72224482e-08 ... -8.72224482e-08
  -7.94609647e-03 -8.72224482e-08]
 [-7.71980919e-07 -7.71980919e-07 -7.71980919e-07 ... -7.71980919e-07
  -7.71980919e-07 -9.85174529e-03]]
[[ 1.37722149e-02 -1.84902058e-05 -1.84902058e-05 ... -1.84902058e-05
  -1.84902058e-05 -1.84902058e-05]
 [-1.03858617e-05 -8.47041299e-02 -1.03858617e-05 ... -1.03858617e-05
  -1.03858617e-05 -1.03858617e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-2.13914397e-03 -2.13914397e-03 -2.1391439

[[-3.76353521e-01 -5.19200747e-04 -5.19200747e-04 ... -5.19200747e-04
  -5.19200747e-04 -5.19200747e-04]
 [-8.23431758e-06 -3.90397003e-02 -8.23431758e-06 ... -8.23431758e-06
  -8.23431758e-06 -8.23431758e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-7.74334463e-06 -7.74334463e-06 -7.74334463e-06 ... -1.41580452e-01
  -7.74334463e-06 -7.74334463e-06]
 [-6.35819631e-04 -6.35819631e-04 -6.35819631e-04 ... -6.35819631e-04
   5.11861276e-02 -6.35819631e-04]
 [-1.44101848e-05 -1.44101848e-05 -1.44101848e-05 ... -1.44101848e-05
  -1.44101848e-05 -1.22154861e-01]]
[[-1.16803301e-01 -4.60783899e-04 -4.60783899e-04 ... -4.60783899e-04
  -4.60783899e-04 -4.60783899e-04]
 [-1.86031104e-05 -8.64945715e-02 -1.86031104e-05 ... -1.86031104e-05
  -1.86031104e-05 -1.86031104e-05]
 [-1.57958992e-04 -1.57958992e-04  1.70423021e-02 ... -1.57958992e-04
  -1.57958992e-04 -1.57958992e-04]
 ...
 [-7.27616792e-06 -7.27616792e-06 -7.2761679

[[ 2.44493984e-01 -2.15995300e-04 -2.15995300e-04 ... -2.15995300e-04
  -2.15995300e-04 -2.15995300e-04]
 [-2.80284496e-03  9.80993793e-01 -2.80284496e-03 ... -2.80284496e-03
  -2.80284496e-03 -2.80284496e-03]
 [-7.63747451e-04 -7.63747451e-04 -7.16080161e-02 ... -7.63747451e-04
  -7.63747451e-04 -7.63747451e-04]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-9.88934722e-08 -9.88934722e-08 -9.88934722e-08 ... -9.88934722e-08
  -1.03007874e-02 -9.88934722e-08]
 [-3.44619165e-03 -3.44619165e-03 -3.44619165e-03 ... -3.44619165e-03
  -3.44619165e-03  6.95809774e-01]]
[[ 7.35439998e-02 -7.19045437e-05 -7.19045437e-05 ... -7.19045437e-05
  -7.19045437e-05 -7.19045437e-05]
 [-1.52049576e-03  3.42023439e-01 -1.52049576e-03 ... -1.52049576e-03
  -1.52049576e-03 -1.52049576e-03]
 [-8.54694991e-05 -8.54694991e-05 -4.33408354e-02 ... -8.54694991e-05
  -8.54694991e-05 -8.54694991e-05]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[ 3.45598031e-02 -5.10972324e-05 -5.10972324e-05 ... -5.10972324e-05
  -5.10972324e-05 -5.10972324e-05]
 [-2.51942860e-05 -1.12981554e-01 -2.51942860e-05 ... -2.51942860e-05
  -2.51942860e-05 -2.51942860e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-8.34150681e-04 -8.34150681e-04 -8.34150681e-04 ...  7.80364863e-02
  -8.34150681e-04 -8.34150681e-04]
 [-1.71526369e-07 -1.71526369e-07 -1.71526369e-07 ... -1.71526369e-07
  -1.59861465e-02 -1.71526369e-07]
 [-1.24026535e-06 -1.24026535e-06 -1.24026535e-06 ... -1.24026535e-06
  -1.24026535e-06 -3.31989471e-02]]
[[ 2.72691372e-02 -4.08290741e-05 -4.08290741e-05 ... -4.08290741e-05
  -4.08290741e-05 -4.08290741e-05]
 [-2.02728508e-05 -1.16568223e-01 -2.02728508e-05 ... -2.02728508e-05
  -2.02728508e-05 -2.02728508e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-8.11598381e-04 -8.11598381e-04 -8.1159838

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.74898513e-05 -4.53542225e-01 -4.74898513e-05 ... -4.74898513e-05
  -4.74898513e-05 -4.74898513e-05]
 [-6.29842968e-04 -6.29842968e-04  7.06017649e-02 ... -6.29842968e-04
  -6.29842968e-04 -6.29842968e-04]
 ...
 [-4.23382520e-06 -4.23382520e-06 -4.23382520e-06 ... -6.76956599e-02
  -4.23382520e-06 -4.23382520e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-5.03209105e-05 -3.83080704e-01 -5.03209105e-05 ... -5.03209105e-05
  -5.03209105e-05 -5.03209105e-05]
 [-6.01025370e-04 -6.01025370e-04  6.73366188e-02 ... -6.01025370e-04
  -6.01025370e-04 -6.01025370e-04]
 ...
 [-4.37092194e-06 -4.37092194e-06 -4.3709219

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.28091665e-04 -4.70242892e-02 -1.28091665e-04 ... -1.28091665e-04
  -1.28091665e-04 -1.28091665e-04]
 [-2.29074042e-07 -2.29074042e-07 -6.64037717e-03 ... -2.29074042e-07
  -2.29074042e-07 -2.29074042e-07]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.74075419e-04 -1.74075419e-04 -1.74075419e-04 ... -1.74075419e-04
  -3.66470074e-02 -1.74075419e-04]
 [-3.62099344e-06 -3.62099344e-06 -3.62099344e-06 ... -3.62099344e-06
  -3.62099344e-06 -1.31253520e-01]]
[[ 1.61493472e-01 -1.30213982e-04 -1.30213982e-04 ... -1.30213982e-04
  -1.30213982e-04 -1.30213982e-04]
 [-1.52005697e-03  2.25137150e-01 -1.52005697e-03 ... -1.52005697e-03
  -1.52005697e-03 -1.52005697e-03]
 [-2.41936438e-04 -2.41936438e-04 -8.12103667e-02 ... -2.41936438e-04
  -2.41936438e-04 -2.41936438e-04]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[ 2.40171093e-01 -2.47264780e-04 -2.47264780e-04 ... -2.47264780e-04
  -2.47264780e-04 -2.47264780e-04]
 [-1.66047961e-04 -3.24742699e-02 -1.66047961e-04 ... -1.66047961e-04
  -1.66047961e-04 -1.66047961e-04]
 [-1.01802775e-07 -1.01802775e-07 -2.66400990e-03 ... -1.01802775e-07
  -1.01802775e-07 -1.01802775e-07]
 ...
 [-8.06480047e-04 -8.06480047e-04 -8.06480047e-04 ...  4.99267478e-02
  -8.06480047e-04 -8.06480047e-04]
 [-2.80331502e-05 -2.80331502e-05 -2.80331502e-05 ... -2.80331502e-05
  -1.58116882e-02 -2.80331502e-05]
 [-1.83420368e-06 -1.83420368e-06 -1.83420368e-06 ... -1.83420368e-06
  -1.83420368e-06 -4.09157810e-02]]
[[ 6.54075085e-02 -7.41557204e-05 -7.41557204e-05 ... -7.41557204e-05
  -7.41557204e-05 -7.41557204e-05]
 [-2.07703400e-03  2.37362181e-01 -2.07703400e-03 ... -2.07703400e-03
  -2.07703400e-03 -2.07703400e-03]
 [-2.03666037e-04 -2.03666037e-04 -1.17285507e-01 ... -2.03666037e-04
  -2.03666037e-04 -2.03666037e-04]
 ...
 [-1.73328947e-07 -1.73328947e-07 -1.7332894

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.14614752e-05 -1.25074699e-01 -3.14614752e-05 ... -3.14614752e-05
  -3.14614752e-05 -3.14614752e-05]
 [-5.19172028e-04 -5.19172028e-04  6.04281978e-02 ... -5.19172028e-04
  -5.19172028e-04 -5.19172028e-04]
 ...
 [-1.28011697e-06 -1.28011697e-06 -1.28011697e-06 ... -1.59013639e-02
  -1.28011697e-06 -1.28011697e-06]
 [-2.46291474e-07 -2.46291474e-07 -2.46291474e-07 ... -2.46291474e-07
  -1.85073781e-02 -2.46291474e-07]
 [-1.49935367e-07 -1.49935367e-07 -1.49935367e-07 ... -1.49935367e-07
  -1.49935367e-07 -4.89008966e-03]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.61965244e-06  7.43402692e-04 -3.61965244e-06 ... -3.61965244e-06
  -3.61965244e-06 -3.61965244e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[ 1.31628197e-01 -1.18591421e-04 -1.18591421e-04 ... -1.18591421e-04
  -1.18591421e-04 -1.18591421e-04]
 [-3.81934546e-03  1.41403573e+00 -3.81934546e-03 ... -3.81934546e-03
  -3.81934546e-03 -3.81934546e-03]
 [-2.11918732e-04 -2.11918732e-04 -1.45908110e-01 ... -2.11918732e-04
  -2.11918732e-04 -2.11918732e-04]
 ...
 [-1.71535928e-07 -1.71535928e-07 -1.71535928e-07 ... -1.90081738e-03
  -1.71535928e-07 -1.71535928e-07]
 [-1.11193850e-07 -1.11193850e-07 -1.11193850e-07 ... -1.11193850e-07
  -8.18056799e-03 -1.11193850e-07]
 [-2.43135905e-03 -2.43135905e-03 -2.43135905e-03 ... -2.43135905e-03
  -2.43135905e-03  4.79410964e-01]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.43958188e-05 -1.84452837e-02 -4.43958188e-05 ... -4.43958188e-05
  -4.43958188e-05 -4.43958188e-05]
 [-4.12340454e-08 -4.12340454e-08 -1.47064032e-03 ... -4.12340454e-08
  -4.12340454e-08 -4.12340454e-08]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.85916174e-05 -4.04644392e-01 -1.85916174e-05 ... -1.85916174e-05
  -1.85916174e-05 -1.85916174e-05]
 [-3.61771140e-04 -3.61771140e-04  4.78071655e-02 ... -3.61771140e-04
  -3.61771140e-04 -3.61771140e-04]
 ...
 [-8.44122060e-06 -8.44122060e-06 -8.44122060e-06 ... -7.83670584e-02
  -8.44122060e-06 -8.44122060e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.19008195e-05 -1.19008195e-05 -1.1900819

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-8.46636826e-05 -1.52350710e-01 -8.46636826e-05 ... -8.46636826e-05
  -8.46636826e-05 -8.46636826e-05]
 [-1.45631157e-03 -1.45631157e-03  1.91787363e-01 ... -1.45631157e-03
  -1.45631157e-03 -1.45631157e-03]
 ...
 [-2.32863854e-06 -2.32863854e-06 -2.32863854e-06 ... -2.23294450e-02
  -2.32863854e-06 -2.32863854e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.19332034e-05 -6.24227410e-02 -4.19332034e-05 ... -4.19332034e-05
  -4.19332034e-05 -4.19332034e-05]
 [-4.12235765e-04 -4.12235765e-04  5.39416123e-02 ... -4.12235765e-04
  -4.12235765e-04 -4.12235765e-04]
 ...
 [-1.16338271e-06 -1.16338271e-06 -1.1633827

[[ 1.34463195e-01 -8.56369982e-05 -8.56369982e-05 ... -8.56369982e-05
  -8.56369982e-05 -8.56369982e-05]
 [-3.07970722e-06 -1.88324172e-03 -3.07970722e-06 ... -3.07970722e-06
  -3.07970722e-06 -3.07970722e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-4.49972166e-05 -4.49972166e-05 -4.49972166e-05 ...  2.74898369e-03
  -4.49972166e-05 -4.49972166e-05]
 [-4.55308531e-05 -4.55308531e-05 -4.55308531e-05 ... -4.55308531e-05
  -1.21605301e-03 -4.55308531e-05]
 [-1.20597803e-06 -1.20597803e-06 -1.20597803e-06 ... -1.20597803e-06
  -1.20597803e-06 -4.10947779e-02]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.20530146e-07 -3.20530146e-07 -1.28830131e-02 ... -3.20530146e-07
  -3.20530146e-07 -3.20530146e-07]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[ 1.55462284e-02 -8.62411664e-06 -8.62411664e-06 ... -8.62411664e-06
  -8.62411664e-06 -8.62411664e-06]
 [-4.18072907e-06 -9.17416698e-02 -4.18072907e-06 ... -4.18072907e-06
  -4.18072907e-06 -4.18072907e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-9.06408648e-04 -9.06408648e-04 -9.06408648e-04 ...  1.14141080e-01
  -9.06408648e-04 -9.06408648e-04]
 [-1.41691687e-07 -1.41691687e-07 -1.41691687e-07 ... -1.41691687e-07
  -1.48318389e-02 -1.41691687e-07]
 [-8.32759710e-07 -8.32759710e-07 -8.32759710e-07 ... -8.32759710e-07
  -8.32759710e-07 -1.87392391e-02]]
[[ 3.06575592e-02 -1.71255105e-05 -1.71255105e-05 ... -1.71255105e-05
  -1.71255105e-05 -1.71255105e-05]
 [-7.36402966e-06 -1.54351055e-01 -7.36402966e-06 ... -7.36402966e-06
  -7.36402966e-06 -7.36402966e-06

[[ 9.14887815e-02 -8.25697792e-05 -8.25697792e-05 ... -8.25697792e-05
  -8.25697792e-05 -8.25697792e-05]
 [-1.23290832e-03  1.88881871e-01 -1.23290832e-03 ... -1.23290832e-03
  -1.23290832e-03 -1.23290832e-03]
 [-1.23540267e-03 -1.23540267e-03  5.75426815e-02 ... -1.23540267e-03
  -1.23540267e-03 -1.23540267e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-6.92629843e-08 -6.92629843e-08 -6.92629843e-08 ... -6.92629843e-08
  -6.61540901e-03 -6.92629843e-08]
 [-1.04066727e-03 -1.04066727e-03 -1.04066727e-03 ... -1.04066727e-03
  -1.04066727e-03  2.18400303e-01]]
[[ 1.57711248e-01 -1.47834767e-04 -1.47834767e-04 ... -1.47834767e-04
  -1.47834767e-04 -1.47834767e-04]
 [-1.98527805e-03  2.94578184e-01 -1.98527805e-03 ... -1.98527805e-03
  -1.98527805e-03 -1.98527805e-03]
 [-3.50640856e-04 -3.50640856e-04 -1.83667900e-01 ... -3.50640856e-04
  -3.50640856e-04 -3.50640856e-04]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.21023501e-06 -1.15986958e-01 -3.21023501e-06 ... -3.21023501e-06
  -3.21023501e-06 -3.21023501e-06]
 [-5.25670984e-05 -5.25670984e-05 -5.32698832e-03 ... -5.25670984e-05
  -5.25670984e-05 -5.25670984e-05]
 ...
 [-5.22681419e-07 -5.22681419e-07 -5.22681419e-07 ... -2.91914175e-03
  -5.22681419e-07 -5.22681419e-07]
 [-4.23713847e-07 -4.23713847e-07 -4.23713847e-07 ... -4.23713847e-07
  -4.74862104e-02 -4.23713847e-07]
 [-1.20110154e-07 -1.20110154e-07 -1.20110154e-07 ... -1.20110154e-07
  -1.20110154e-07 -4.64925296e-03]]
[[-6.05140203e-02 -4.31873476e-05 -4.31873476e-05 ... -4.31873476e-05
  -4.31873476e-05 -4.31873476e-05]
 [-2.80119154e-06 -9.55057648e-02 -2.80119154e-06 ... -2.80119154e-06
  -2.80119154e-06 -2.80119154e-06]
 [-7.86692319e-05 -7.86692319e-05  1.35190580e-02 ... -7.86692319e-05
  -7.86692319e-05 -7.86692319e-05]
 ...
 [-3.40434220e-06 -3.40434220e-06 -3.4043422

[[ 2.23922511e-02 -4.62584209e-04 -4.62584209e-04 ... -4.62584209e-04
  -4.62584209e-04 -4.62584209e-04]
 [-1.86742210e-06 -7.56484599e-02 -1.86742210e-06 ... -1.86742210e-06
  -1.86742210e-06 -1.86742210e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-2.63077527e-05 -2.63077527e-05 -2.63077527e-05 ... -1.01490994e-01
  -2.63077527e-05 -2.63077527e-05]
 [-7.25194216e-04 -7.25194216e-04 -7.25194216e-04 ... -7.25194216e-04
   7.82935554e-02 -7.25194216e-04]
 [-7.12341464e-06 -7.12341464e-06 -7.12341464e-06 ... -7.12341464e-06
  -7.12341464e-06 -2.58832983e-01]]
[[ 1.52032186e-02 -3.13943110e-04 -3.13943110e-04 ... -3.13943110e-04
  -3.13943110e-04 -3.13943110e-04]
 [-1.17261854e-06 -4.57391304e-02 -1.17261854e-06 ... -1.17261854e-06
  -1.17261854e-06 -1.17261854e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.95969636e-05 -1.95969636e-05 -1.9596963

[[ 1.33275849e-02 -8.96176563e-06 -8.96176563e-06 ... -8.96176563e-06
  -8.96176563e-06 -8.96176563e-06]
 [-3.95388218e-06 -1.38936182e-01 -3.95388218e-06 ... -3.95388218e-06
  -3.95388218e-06 -3.95388218e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.79809186e-03 -1.79809186e-03 -1.79809186e-03 ...  2.94472065e-01
  -1.79809186e-03 -1.79809186e-03]
 [-1.03404248e-07 -1.03404248e-07 -1.03404248e-07 ... -1.03404248e-07
  -1.37567920e-02 -1.03404248e-07]
 [-3.94137669e-07 -3.94137669e-07 -3.94137669e-07 ... -3.94137669e-07
  -3.94137669e-07 -3.18410429e-02]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-6.34708200e-06 -2.08064026e-01 -6.34708200e-06 ... -6.34708200e-06
  -6.34708200e-06 -6.34708200e-06]
 [-1.39541181e-04 -1.39541181e-04  2.91070626e-02 ... -1.39541181e-04
  -1.39541181e-04 -1.39541181e-04]
 ...
 [-1.58405405e-06 -1.58405405e-06 -1.5840540

[[ 7.39508925e-02 -5.82213027e-05 -5.82213027e-05 ... -5.82213027e-05
  -5.82213027e-05 -5.82213027e-05]
 [-4.16596055e-06  1.45065461e-03 -4.16596055e-06 ... -4.16596055e-06
  -4.16596055e-06 -4.16596055e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-4.57481222e-05 -4.57481222e-05 -4.57481222e-05 ...  5.57868623e-03
  -4.57481222e-05 -4.57481222e-05]
 [-4.56681895e-05 -4.56681895e-05 -4.56681895e-05 ... -4.56681895e-05
  -4.43951074e-03 -4.56681895e-05]
 [-9.10048492e-07 -9.10048492e-07 -9.10048492e-07 ... -9.10048492e-07
  -9.10048492e-07 -8.16826570e-02]]
[[ 4.80813268e-02 -3.90625874e-05 -3.90625874e-05 ... -3.90625874e-05
  -3.90625874e-05 -3.90625874e-05]
 [-2.42243407e-06  8.43358705e-04 -2.42243407e-06 ... -2.42243407e-06
  -2.42243407e-06 -2.42243407e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-6.69333702e-05 -6.69333702e-05 -6.6933370

[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [-0.00010078  0.03654606 -0.00010078 ... -0.00010078 -0.00010078
  -0.00010078]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-7.56463572e-05  1.69661451e-02 -7.56463572e-05 ... -7.56463572e-05
  -7.56463572e-05 -7.56463572e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 

[[ 2.01497342e-03 -1.42700848e-06 -1.42700848e-06 ... -1.42700848e-06
  -1.42700848e-06 -1.42700848e-06]
 [-2.06651812e-05 -6.99087697e-01 -2.06651812e-05 ... -2.06651812e-05
  -2.06651812e-05 -2.06651812e-05]
 [-5.73040744e-04 -5.73040744e-04  1.34889410e-01 ... -5.73040744e-04
  -5.73040744e-04 -5.73040744e-04]
 ...
 [-2.28565383e-04 -2.28565383e-04 -2.28565383e-04 ... -1.23253380e-02
  -2.28565383e-04 -2.28565383e-04]
 [-1.69611367e-08 -1.69611367e-08 -1.69611367e-08 ... -1.69611367e-08
  -1.94562143e-03 -1.69611367e-08]
 [-5.03931544e-08 -5.03931544e-08 -5.03931544e-08 ... -5.03931544e-08
  -5.03931544e-08 -4.38417724e-03]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.88892632e-05 -6.89014607e-01 -2.88892632e-05 ... -2.88892632e-05
  -2.88892632e-05 -2.88892632e-05]
 [-5.48870489e-04 -5.48870489e-04  1.26309772e-01 ... -5.48870489e-04
  -5.48870489e-04 -5.48870489e-04]
 ...
 [-7.91323550e-06 -7.91323550e-06 -7.9132355

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.13330608e-04 -1.31434418e-01 -3.13330608e-04 ... -3.13330608e-04
  -3.13330608e-04 -3.13330608e-04]
 [-1.41905706e-04 -1.41905706e-04  1.85941573e-02 ... -1.41905706e-04
  -1.41905706e-04 -1.41905706e-04]
 ...
 [-4.10098313e-06 -4.10098313e-06 -4.10098313e-06 ... -2.43654361e-02
  -4.10098313e-06 -4.10098313e-06]
 [-4.26496285e-07 -4.26496285e-07 -4.26496285e-07 ... -4.26496285e-07
  -4.64160115e-02 -4.26496285e-07]
 [-6.27955873e-08 -6.27955873e-08 -6.27955873e-08 ... -6.27955873e-08
  -6.27955873e-08 -4.51516437e-03]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-5.96015358e-04  1.57067677e-01 -5.96015358e-04 ... -5.96015358e-04
  -5.96015358e-04 -5.96015358e-04]
 [-3.15070221e-07 -3.15070221e-07 -1.79436070e-02 ... -3.15070221e-07
  -3.15070221e-07 -3.15070221e-07]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[-1.11792999e-01 -1.22116118e-04 -1.22116118e-04 ... -1.22116118e-04
  -1.22116118e-04 -1.22116118e-04]
 [-5.05724596e-05 -2.83390615e-01 -5.05724596e-05 ... -5.05724596e-05
  -5.05724596e-05 -5.05724596e-05]
 [-2.07077001e-04 -2.07077001e-04  4.47419017e-02 ... -2.07077001e-04
  -2.07077001e-04 -2.07077001e-04]
 ...
 [-1.54672078e-04 -1.54672078e-04 -1.54672078e-04 ... -5.36673729e-02
  -1.54672078e-04 -1.54672078e-04]
 [-1.58447675e-04 -1.58447675e-04 -1.58447675e-04 ... -1.58447675e-04
   2.04395976e-02 -1.58447675e-04]
 [-7.56808850e-07 -7.56808850e-07 -7.56808850e-07 ... -7.56808850e-07
  -7.56808850e-07 -5.44939607e-02]]
[[-7.86698984e-01 -3.40646670e-04 -3.40646670e-04 ... -3.40646670e-04
  -3.40646670e-04 -3.40646670e-04]
 [-2.47103425e-06 -3.11603565e-02 -2.47103425e-06 ... -2.47103425e-06
  -2.47103425e-06 -2.47103425e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.22503418e-05 -1.22503418e-05 -1.2250341

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.27156036e-05  6.06521342e-03 -1.27156036e-05 ... -1.27156036e-05
  -1.27156036e-05 -1.27156036e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.50342831e-05  3.04602996e-03 -3.50342831e-05 ... -3.50342831e-05
  -3.50342831e-05 -3.50342831e-05

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.36205882e-05 -2.15696967e-01 -4.36205882e-05 ... -4.36205882e-05
  -4.36205882e-05 -4.36205882e-05]
 [-8.30561166e-04 -8.30561166e-04  1.86509614e-01 ... -8.30561166e-04
  -8.30561166e-04 -8.30561166e-04]
 ...
 [-3.48253197e-06 -3.48253197e-06 -3.48253197e-06 ... -3.52712285e-02
  -3.48253197e-06 -3.48253197e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
[[ 1.47014719e-02 -8.78407637e-06 -8.78407637e-06 ... -8.78407637e-06
  -8.78407637e-06 -8.78407637e-06]
 [-1.62745929e-04  1.25688101e-01 -1.62745929e-04 ... -1.62745929e-04
  -1.62745929e-04 -1.62745929e-04]
 [-1.30727900e-03 -1.30727900e-03  2.70862551e-01 ... -1.30727900e-03
  -1.30727900e-03 -1.30727900e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[-3.75790339e-01 -1.36331156e-04 -1.36331156e-04 ... -1.36331156e-04
  -1.36331156e-04 -1.36331156e-04]
 [-8.28338512e-07 -1.98169221e-02 -8.28338512e-07 ... -8.28338512e-07
  -8.28338512e-07 -8.28338512e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-5.29011238e-06 -5.29011238e-06 -5.29011238e-06 ... -5.29458213e-02
  -5.29011238e-06 -5.29011238e-06]
 [-3.74339365e-04 -3.74339365e-04 -3.74339365e-04 ... -3.74339365e-04
   5.15659193e-02 -3.74339365e-04]
 [-2.16308814e-06 -2.16308814e-06 -2.16308814e-06 ... -2.16308814e-06
  -2.16308814e-06 -1.05774487e-01]]
[[-5.89012065e-01 -3.33077214e-04 -3.33077214e-04 ... -3.33077214e-04
  -3.33077214e-04 -3.33077214e-04]
 [-1.85164054e-06 -4.38613525e-02 -1.85164054e-06 ... -1.85164054e-06
  -1.85164054e-06 -1.85164054e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.31900181e-05 -1.31900181e-05 -1.3190018

[[-1.16039318e-02 -1.25299097e-05 -1.25299097e-05 ... -1.25299097e-05
  -1.25299097e-05 -1.25299097e-05]
 [-1.17942959e-05 -6.24686726e-01 -1.17942959e-05 ... -1.17942959e-05
  -1.17942959e-05 -1.17942959e-05]
 [-2.85029390e-04 -2.85029390e-04  8.47044004e-02 ... -2.85029390e-04
  -2.85029390e-04 -2.85029390e-04]
 ...
 [-5.54826566e-06 -5.54826566e-06 -5.54826566e-06 ... -5.09207773e-02
  -5.54826566e-06 -5.54826566e-06]
 [-2.22356518e-05 -2.22356518e-05 -2.22356518e-05 ... -2.22356518e-05
  -4.73907330e-05 -2.22356518e-05]
 [-1.08613612e-07 -1.08613612e-07 -1.08613612e-07 ... -1.08613612e-07
  -1.08613612e-07 -8.24495861e-03]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.02954585e-05 -1.02954585e-05 -1.0295458

[[ 1.41558629e-01 -8.31657707e-05 -8.31657707e-05 ... -8.31657707e-05
  -8.31657707e-05 -8.31657707e-05]
 [-1.65615493e-03  5.84977837e-01 -1.65615493e-03 ... -1.65615493e-03
  -1.65615493e-03 -1.65615493e-03]
 [-2.23072005e-04 -2.23072005e-04 -9.13378803e-02 ... -2.23072005e-04
  -2.23072005e-04 -2.23072005e-04]
 ...
 [-1.30042826e-07 -1.30042826e-07 -1.30042826e-07 ... -1.32765892e-03
  -1.30042826e-07 -1.30042826e-07]
 [-8.36707872e-08 -8.36707872e-08 -8.36707872e-08 ... -8.36707872e-08
  -7.23865733e-03 -8.36707872e-08]
 [-9.44982041e-04 -9.44982041e-04 -9.44982041e-04 ... -9.44982041e-04
  -9.44982041e-04  2.03231612e-01]]
[[ 3.42684411e-02 -2.14354967e-05 -2.14354967e-05 ... -2.14354967e-05
  -2.14354967e-05 -2.14354967e-05]
 [-3.40008535e-04 -2.58754118e-02 -3.40008535e-04 ... -3.40008535e-04
  -3.40008535e-04 -3.40008535e-04]
 [-6.43762098e-05 -6.43762098e-05 -1.72133675e-02 ... -6.43762098e-05
  -6.43762098e-05 -6.43762098e-05]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.15278202e-05 -4.67705356e-01 -3.15278202e-05 ... -3.15278202e-05
  -3.15278202e-05 -3.15278202e-05]
 [-4.40748029e-04 -4.40748029e-04  1.42732167e-01 ... -4.40748029e-04
  -4.40748029e-04 -4.40748029e-04]
 ...
 [-5.38374629e-06 -5.38374629e-06 -5.38374629e-06 ... -5.61052082e-02
  -5.38374629e-06 -5.38374629e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-6.85951498e-05 -3.09192036e-02 -6.85951498e-05 ... -6.85951498e-05
  -6.85951498e-05 -6.85951498e-05]
 [-1.56696441e-03 -1.56696441e-03  4.88099812e-01 ... -1.56696441e-03
  -1.56696441e-03 -1.56696441e-03]
 ...
 [-8.70475794e-07 -8.70475794e-07 -8.7047579

[[-7.65945577e-01 -2.64016161e-04 -2.64016161e-04 ... -2.64016161e-04
  -2.64016161e-04 -2.64016161e-04]
 [-1.86820814e-06 -4.82452474e-02 -1.86820814e-06 ... -1.86820814e-06
  -1.86820814e-06 -1.86820814e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.21848453e-05 -1.21848453e-05 -1.21848453e-05 ... -1.32159613e-01
  -1.21848453e-05 -1.21848453e-05]
 [-8.56538855e-04 -8.56538855e-04 -8.56538855e-04 ... -8.56538855e-04
   1.36312366e-01 -8.56538855e-04]
 [-4.28722790e-06 -4.28722790e-06 -4.28722790e-06 ... -4.28722790e-06
  -4.28722790e-06 -2.69348292e-01]]
[[-2.79064578e-01 -3.33405145e-04 -3.33405145e-04 ... -3.33405145e-04
  -3.33405145e-04 -3.33405145e-04]
 [-1.89195618e-06 -4.76940755e-02 -1.89195618e-06 ... -1.89195618e-06
  -1.89195618e-06 -1.89195618e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.26866190e-05 -1.26866190e-05 -1.2686619

[[ 1.66192281e-02 -3.48118311e-04 -3.48118311e-04 ... -3.48118311e-04
  -3.48118311e-04 -3.48118311e-04]
 [-1.83118067e-06 -4.86317751e-02 -1.83118067e-06 ... -1.83118067e-06
  -1.83118067e-06 -1.83118067e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.41575584e-05 -1.41575584e-05 -1.41575584e-05 ... -1.12961087e-01
  -1.41575584e-05 -1.41575584e-05]
 [-7.30908789e-04 -7.30908789e-04 -7.30908789e-04 ... -7.30908789e-04
   1.05754519e-01 -7.30908789e-04]
 [-9.63594154e-06 -9.63594154e-06 -9.63594154e-06 ... -9.63594154e-06
  -9.63594154e-06 -2.09124669e-01]]
[[ 1.67665793e-02 -3.45616401e-04 -3.45616401e-04 ... -3.45616401e-04
  -3.45616401e-04 -3.45616401e-04]
 [-1.85386806e-06 -4.80516042e-02 -1.85386806e-06 ... -1.85386806e-06
  -1.85386806e-06 -1.85386806e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.44273239e-05 -1.44273239e-05 -1.4427323

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.66528134e-05  3.91565314e-02 -3.66528134e-05 ... -3.66528134e-05
  -3.66528134e-05 -3.66528134e-05]
 [-2.60202437e-04 -2.60202437e-04  7.07446292e-02 ... -2.60202437e-04
  -2.60202437e-04 -2.60202437e-04]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
[[ 3.52786391e-01 -1.23285252e-04 -1.23285252e-04 ... -1.23285252e-04
  -1.23285252e-04 -1.23285252e-04]
 [-1.82302471e-03  1.96440200e+00 -1.82302471e-03 ... -1.82302471e-03
  -1.82302471e-03 -1.82302471e-03]
 [-1.67429542e-04 -1.67429542e-04 -1.37407095e-01 ... -1.67429542e-04
  -1.67429542e-04 -1.67429542e-04]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-6.34801578e-05 -1.81977461e-01 -6.34801578e-05 ... -6.34801578e-05
  -6.34801578e-05 -6.34801578e-05]
 [-1.23560014e-04 -1.23560014e-04  3.71077335e-02 ... -1.23560014e-04
  -1.23560014e-04 -1.23560014e-04]
 ...
 [-6.35127328e-06 -6.35127328e-06 -6.35127328e-06 ... -3.48381884e-02
  -6.35127328e-06 -6.35127328e-06]
 [-1.99731487e-05 -1.99731487e-05 -1.99731487e-05 ... -1.99731487e-05
  -1.48066647e-02 -1.99731487e-05]
 [-8.03202177e-07 -8.03202177e-07 -8.03202177e-07 ... -8.03202177e-07
  -8.03202177e-07 -7.35486289e-02]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.26895143e-04  7.88194813e-02 -1.26895143e-04 ... -1.26895143e-04
  -1.26895143e-04 -1.26895143e-04]
 [-3.78561014e-08 -3.78561014e-08 -2.45136703e-03 ... -3.78561014e-08
  -3.78561014e-08 -3.78561014e-08]
 ...
 [-2.68183052e-04 -2.68183052e-04 -2.6818305

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.17037263e-03  7.55358406e-01 -1.17037263e-03 ... -1.17037263e-03
  -1.17037263e-03 -1.17037263e-03]
 [-1.46215487e-06 -1.46215487e-06 -8.92069674e-02 ... -1.46215487e-06
  -1.46215487e-06 -1.46215487e-06]
 ...
 [-2.45049197e-07 -2.45049197e-07 -2.45049197e-07 ... -1.32130920e-03
  -2.45049197e-07 -2.45049197e-07]
 [-1.55637522e-07 -1.55637522e-07 -1.55637522e-07 ... -1.55637522e-07
  -2.05780643e-02 -1.55637522e-07]
 [-2.20078595e-04 -2.20078595e-04 -2.20078595e-04 ... -2.20078595e-04
  -2.20078595e-04  5.80149823e-02]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.29597772e-03  7.29111887e-01 -1.29597772e-03 ... -1.29597772e-03
  -1.29597772e-03 -1.29597772e-03]
 [-2.14906953e-06 -2.14906953e-06 -1.25396420e-01 ... -2.14906953e-06
  -2.14906953e-06 -2.14906953e-06]
 ...
 [-4.92335627e-07 -4.92335627e-07 -4.9233562

[[ 1.19152652e-01 -7.99167143e-05 -7.99167143e-05 ... -7.99167143e-05
  -7.99167143e-05 -7.99167143e-05]
 [-9.46527049e-04  2.29558912e-01 -9.46527049e-04 ... -9.46527049e-04
  -9.46527049e-04 -9.46527049e-04]
 [-2.10986989e-04 -2.10986989e-04 -1.13696151e-01 ... -2.10986989e-04
  -2.10986989e-04 -2.10986989e-04]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-7.83014033e-08 -7.83014033e-08 -7.83014033e-08 ... -7.83014033e-08
  -9.63571089e-03 -7.83014033e-08]
 [-6.93525236e-04 -6.93525236e-04 -6.93525236e-04 ... -6.93525236e-04
  -6.93525236e-04  1.04465619e-01]]
[[ 1.06004455e-01 -7.48831348e-05 -7.48831348e-05 ... -7.48831348e-05
  -7.48831348e-05 -7.48831348e-05]
 [-8.83824624e-04  1.69909443e-01 -8.83824624e-04 ... -8.83824624e-04
  -8.83824624e-04 -8.83824624e-04]
 [-2.25355090e-04 -2.25355090e-04 -1.05947991e-01 ... -2.25355090e-04
  -2.25355090e-04 -2.25355090e-04]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[ 3.00723054e-02 -9.59595705e-06 -9.59595705e-06 ... -9.59595705e-06
  -9.59595705e-06 -9.59595705e-06]
 [-5.77890204e-06 -1.69026610e-01 -5.77890204e-06 ... -5.77890204e-06
  -5.77890204e-06 -5.77890204e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.09723289e-03 -1.09723289e-03 -1.09723289e-03 ...  4.62239925e-01
  -1.09723289e-03 -1.09723289e-03]
 [-1.43556527e-07 -1.43556527e-07 -1.43556527e-07 ... -1.43556527e-07
  -2.28609080e-02 -1.43556527e-07]
 [-7.24184485e-07 -7.24184485e-07 -7.24184485e-07 ... -7.24184485e-07
  -7.24184485e-07 -4.27120396e-02]]
[[ 2.95610449e-02 -9.56678524e-06 -9.56678524e-06 ... -9.56678524e-06
  -9.56678524e-06 -9.56678524e-06]
 [-5.95455105e-06 -1.60050253e-01 -5.95455105e-06 ... -5.95455105e-06
  -5.95455105e-06 -5.95455105e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.14565282e-03 -1.14565282e-03 -1.1456528

[[ 2.10768462e-01 -2.72876147e-04 -2.72876147e-04 ... -2.72876147e-04
  -2.72876147e-04 -2.72876147e-04]
 [-7.51213605e-06 -1.55618045e-02 -7.51213605e-06 ... -7.51213605e-06
  -7.51213605e-06 -7.51213605e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-6.05871258e-05 -6.05871258e-05 -6.05871258e-05 ... -6.20264345e-02
  -6.05871258e-05 -6.05871258e-05]
 [-4.35747168e-04 -4.35747168e-04 -4.35747168e-04 ... -4.35747168e-04
   4.66870262e-02 -4.35747168e-04]
 [-8.39058840e-06 -8.39058840e-06 -8.39058840e-06 ... -8.39058840e-06
  -8.39058840e-06 -1.79015793e-01]]
[[ 6.24339243e-01 -2.17120297e-04 -2.17120297e-04 ... -2.17120297e-04
  -2.17120297e-04 -2.17120297e-04]
 [-1.91797218e-05  2.54628441e-02 -1.91797218e-05 ... -1.91797218e-05
  -1.91797218e-05 -1.91797218e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.72468499e-04 -1.72468499e-04 -1.7246849

[[-1.97095401e-01 -2.83159016e-04 -2.83159016e-04 ... -2.83159016e-04
  -2.83159016e-04 -2.83159016e-04]
 [-1.98723044e-06 -3.43366330e-02 -1.98723044e-06 ... -1.98723044e-06
  -1.98723044e-06 -1.98723044e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.34186490e-05 -1.34186490e-05 -1.34186490e-05 ... -1.00509299e-01
  -1.34186490e-05 -1.34186490e-05]
 [-5.77183608e-04 -5.77183608e-04 -5.77183608e-04 ... -5.77183608e-04
   9.76961600e-02 -5.77183608e-04]
 [-6.54254369e-06 -6.54254369e-06 -6.54254369e-06 ... -6.54254369e-06
  -6.54254369e-06 -7.23463696e-02]]
[[-2.33605866e-03 -2.93410982e-04 -2.93410982e-04 ... -2.93410982e-04
  -2.93410982e-04 -2.93410982e-04]
 [-1.98344089e-06 -3.36878320e-02 -1.98344089e-06 ... -1.98344089e-06
  -1.98344089e-06 -1.98344089e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.34914451e-05 -1.34914451e-05 -1.3491445

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.18205639e-05  1.21261382e-02 -2.18205639e-05 ... -2.18205639e-05
  -2.18205639e-05 -2.18205639e-05]
 [-8.00872673e-05 -8.00872673e-05  2.86149627e-02 ... -8.00872673e-05
  -8.00872673e-05 -8.00872673e-05]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
[[ 2.10131374e-01 -7.59703968e-05 -7.59703968e-05 ... -7.59703968e-05
  -7.59703968e-05 -7.59703968e-05]
 [-9.06157239e-04  4.97121550e-01 -9.06157239e-04 ... -9.06157239e-04
  -9.06157239e-04 -9.06157239e-04]
 [-1.25706736e-04 -1.25706736e-04 -9.77894195e-02 ... -1.25706736e-04
  -1.25706736e-04 -1.25706736e-04]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.39712162e-07 -5.51057521e-03 -2.39712162e-07 ... -2.39712162e-07
  -2.39712162e-07 -2.39712162e-07]
 [-2.13183421e-07 -2.13183421e-07 -1.63813619e-02 ... -2.13183421e-07
  -2.13183421e-07 -2.13183421e-07]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.40727554e-05 -4.40727554e-05 -4.40727554e-05 ... -4.40727554e-05
  -2.27751718e-02 -4.40727554e-05]
 [-2.92883417e-07 -2.92883417e-07 -2.92883417e-07 ... -2.92883417e-07
  -2.92883417e-07 -2.45469242e-02]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-6.14029364e-07 -1.40766545e-02 -6.14029364e-07 ... -6.14029364e-07
  -6.14029364e-07 -6.14029364e-07]
 [-1.87220243e-07 -1.87220243e-07 -1.42689581e-02 ... -1.87220243e-07
  -1.87220243e-07 -1.87220243e-07]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.61481124e-05 -1.05673653e-02 -1.61481124e-05 ... -1.61481124e-05
  -1.61481124e-05 -1.61481124e-05]
 [-8.38467794e-09 -8.38467794e-09 -5.11161226e-04 ... -8.38467794e-09
  -8.38467794e-09 -8.38467794e-09]
 ...
 [-1.95075996e-03 -1.95075996e-03 -1.95075996e-03 ...  7.43361839e-01
  -1.95075996e-03 -1.95075996e-03]
 [-7.98446594e-06 -7.98446594e-06 -7.98446594e-06 ... -7.98446594e-06
  -5.77568625e-03 -7.98446594e-06]
 [-3.10878802e-07 -3.10878802e-07 -3.10878802e-07 ... -3.10878802e-07
  -3.10878802e-07 -3.05647175e-02]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-8.74627155e-06 -2.91986399e-02 -8.74627155e-06 ... -8.74627155e-06
  -8.74627155e-06 -8.74627155e-06]
 [-1.67064711e-07 -1.67064711e-07 -1.01822850e-02 ... -1.67064711e-07
  -1.67064711e-07 -1.67064711e-07]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.0000000

[[ 3.34830080e-01 -1.50163983e-04 -1.50163983e-04 ... -1.50163983e-04
  -1.50163983e-04 -1.50163983e-04]
 [-1.14993933e-05  1.08395110e-02 -1.14993933e-05 ... -1.14993933e-05
  -1.14993933e-05 -1.14993933e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-1.14574439e-04 -1.14574439e-04 -1.14574439e-04 ...  1.72077916e-02
  -1.14574439e-04 -1.14574439e-04]
 [-1.91110156e-04 -1.91110156e-04 -1.91110156e-04 ... -1.91110156e-04
  -7.76798906e-03 -1.91110156e-04]
 [-3.85295031e-06 -3.85295031e-06 -3.85295031e-06 ... -3.85295031e-06
  -3.85295031e-06 -2.10308424e-01]]
[[ 5.76285284e-02 -3.00994921e-05 -3.00994921e-05 ... -3.00994921e-05
  -3.00994921e-05 -3.00994921e-05]
 [-1.86771114e-05  1.33360818e-02 -1.86771114e-05 ... -1.86771114e-05
  -1.86771114e-05 -1.86771114e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-5.06365175e-04 -5.06365175e-04 -5.0636517

[[ 1.49369124e-03 -6.79836728e-07 -6.79836728e-07 ... -6.79836728e-07
  -6.79836728e-07 -6.79836728e-07]
 [-3.57765431e-07 -1.30827241e-02 -3.57765431e-07 ... -3.57765431e-07
  -3.57765431e-07 -3.57765431e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-4.51570068e-05 -4.51570068e-05 -4.51570068e-05 ... -1.64079621e-03
  -4.51570068e-05 -4.51570068e-05]
 [-1.59313756e-08 -1.59313756e-08 -1.59313756e-08 ... -1.59313756e-08
  -2.36222900e-03 -1.59313756e-08]
 [-6.58521167e-08 -6.58521167e-08 -6.58521167e-08 ... -6.58521167e-08
  -6.58521167e-08 -3.15558023e-03]]
[[ 1.36511625e-02 -6.21740765e-06 -6.21740765e-06 ... -6.21740765e-06
  -6.21740765e-06 -6.21740765e-06]
 [-3.55859004e-06 -1.29281674e-01 -3.55859004e-06 ... -3.55859004e-06
  -3.55859004e-06 -3.55859004e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [-4.30675094e-04 -4.30675094e-04 -4.3067509

[[ 1.30959511e-03 -6.03514557e-07 -6.03514557e-07 ... -6.03514557e-07
  -6.03514557e-07 -6.03514557e-07]
 [-1.36908559e-05 -2.55036260e-01 -1.36908559e-05 ... -1.36908559e-05
  -1.36908559e-05 -1.36908559e-05]
 [-2.37813124e-04 -2.37813124e-04  9.50821866e-02 ... -2.37813124e-04
  -2.37813124e-04 -2.37813124e-04]
 ...
 [-4.04574759e-05 -4.04574759e-05 -4.04574759e-05 ... -5.27696095e-02
  -4.04574759e-05 -4.04574759e-05]
 [-1.03805333e-08 -1.03805333e-08 -1.03805333e-08 ... -1.03805333e-08
  -1.40146929e-03 -1.03805333e-08]
 [-6.42587702e-08 -6.42587702e-08 -6.42587702e-08 ... -6.42587702e-08
  -6.42587702e-08 -2.90460010e-03]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.51509742e-05 -2.48447394e-01 -1.51509742e-05 ... -1.51509742e-05
  -1.51509742e-05 -1.51509742e-05]
 [-2.54103406e-04 -2.54103406e-04  9.89005660e-02 ... -2.54103406e-04
  -2.54103406e-04 -2.54103406e-04]
 ...
 [-2.14532008e-06 -2.14532008e-06 -2.1453200

In [286]:
A , 

array([[0.98913043, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.98490566, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.98989899, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.98830409, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.984375  ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.98642534]])

In [287]:
A_gd

array([[9.90938218e-01, 4.49334262e-06, 4.49334262e-06, ...,
        4.49334262e-06, 4.49334262e-06, 4.49334262e-06],
       [3.17874842e-05, 9.63555952e-01, 3.17874842e-05, ...,
        3.17874842e-05, 3.17874842e-05, 3.17874842e-05],
       [1.09943981e-05, 1.09943981e-05, 9.96073392e-01, ...,
        1.09943981e-05, 1.09943981e-05, 1.09943981e-05],
       ...,
       [3.25224858e-05, 3.25224858e-05, 3.25224858e-05, ...,
        9.92273874e-01, 3.25224858e-05, 3.25224858e-05],
       [7.78370378e-06, 7.78370378e-06, 7.78370378e-06, ...,
        7.78370378e-06, 9.98027843e-01, 7.78370378e-06],
       [1.54933542e-05, 1.54933542e-05, 1.54933542e-05, ...,
        1.54933542e-05, 1.54933542e-05, 9.90512031e-01]])