In [1]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.cluster import  MiniBatchKMeans
import numpy as np
import pandas as pd
from __future__ import division

%autosave 0 

Autosave disabled


In [2]:


class HMM (object):
             def __init__(self,A,B,PI):
                 self.A=A
                 self.B=B
                 self.PI=PI   
def viterbi(obs,Modelo1,PI):
    
    delta=np.zeros((len(obs)+1,len(Modelo1.A)))
    phi=np.zeros((len(obs)+1,len(A)))+666
    path =np.zeros(len(obs)+1)
    T=len(obs)
    Modelo1.PI = PI
    delta[0,:]= Modelo1.PI * Modelo1.B[:,obs[0]]
    phi[0,:]=666
    for t in range(len(obs)):
        for j in range(delta.shape[1]):

            delta [t+1,j]=np.max(delta[t] * A[:,j]) * B[j,obs[t]]
            phi[t+1,j]= np.argmax(delta[t] * A[:,j])
    path[T]=int(np.argmax(delta[T,:]))
    for i in np.arange(T-1,0,-1):
        #print (i,phi[i+1,int(path[i+1])])
        path[i]=phi[i+1,int(path[i+1])]
    return(path)
def cuantizar_xy(xy, cc):
    xycuant=cc
    out=np.power(xycuant-xy,2).sum(axis=1).argmin()
    return out
    
def path_to_xy(path,ccxy):
    estimated= pd.DataFrame(path.astype(int).T)
    estimated.columns=[['Path_vit']]
    estimated['xcuant'] = estimated['Path_vit'].apply(lambda x: ccxy[x,0])
    estimated['ycuant'] = estimated['Path_vit'].apply(lambda x: ccxy[x,1])                                
    return (estimated)
def quantized(xyth,ccxyth):
    xythcuant=np.argmin(np.linalg.norm(xyth-ccxyth,axis=1))
    x,y=ccxyth[xythcuant,:2]
    return ((x,y),(xythcuant))



In [3]:
def Markov_A_2_grafo(A,ccxyth):
    dists=np.zeros(A.shape)
    for i in range(A.shape[0]):
        for j in range (A.shape[1]):
            if A[i,j]!=0 :
                dists[i,j]= np.linalg.norm(ccxyth[i]-ccxyth[j])    
    
    
    con = np.where(dists==0,np.inf,dists)
    graphe2=grafo(ccxyth,con)
    return graphe2


class node(object):
    def __init__(self,x,y):
        self.x=x
        self.y=y
        
        
class grafo (object):
             def __init__(self,nodos,conec):
                 self.nodos=nodos
                 self.conec=conec        

def dijkstra(nodoinicial,nodofinal,graphe):
    

    numnodos= len(graphe.nodos)
    con = graphe.conec
    D= np.ones(numnodos)*np.inf
    Prv= np.ones(numnodos)*np.inf
    V= np.zeros(numnodos)
    a = nodoinicial
    D[a]=0
    Prv[a]=0
    Prv[np.where(con[a]!=np.inf)]=a
    V[a]=1
    Dacc=D[a]
    ########
    D=np.minimum(D,con[a]+D[a])
    cont=0
    sucess=False
    while(sucess==False):
        a = np.argmin(D+np.where (V==1,np.inf, V))
        Dacc=D[a]
        Prv[np.where(D>(con[a]+Dacc) )]=a
        V[a]=1
        D=np.minimum(D,con[a]+Dacc)
        if (a== nodofinal):
            print("RUTA CALCULADA ")
            sucess=True
    rutainv=[]
    rutainv.append(nodofinal)
    while(rutainv[-1]!=nodoinicial):
        prv=Prv[int(rutainv[-1])]
        rutainv.append(prv)

    ruta=[]
    for n in reversed(rutainv):
        ruta.append(n)
    return(ruta)


In [4]:
only_nice=True
data=pd.read_csv('lecturasconodometria_nice.txt')
#data=data.iloc[:5000,:]

cols=['x','y','theta']
n_reads=data.shape[1]-3
n_reads
etiquetas=[]
for i in range (n_reads):
    etiquetas.append('R'+str(i))

        
for lab in cols:
    etiquetas.append(lab)


data.columns=etiquetas

if (only_nice!=True):
    print("NOT ONLY NICE")
    data2=pd.read_csv('lecturasconodometria.txt')
    data2.columns=etiquetas
    data3= pd.concat((data,data2))
    data=data3






####
#index = data[data.y<-1].index
#data=data.drop(index)
data.describe()



#####

xyth=data[['x','y','theta']]

lecs=data.iloc[:,0:n_reads]


data.describe()


R0            R1            R2            R3            R4  \
count  23877.000000  23877.000000  23877.000000  23877.000000  23877.000000   
mean       3.190143      3.189229      3.192182      3.194631      3.196241   
std        2.054171      2.065934      2.079633      2.096674      2.108123   
min        0.406166      0.404345      0.403152      0.401979      0.400827   
25%        1.628477      1.623511      1.618123      1.613172      1.609086   
50%        2.475462      2.465552      2.457282      2.447728      2.441308   
75%        4.466963      4.478095      4.493530      4.490005      4.502109   
max       12.282996     13.500000     12.294272     12.283157     13.500000   

                 R5            R6            R7            R8            R9  \
count  23877.000000  23877.000000  23877.000000  23877.000000  23877.000000   
mean       3.194398      3.190053      3.191011      3.194637      3.191882   
std        2.115277      2.120580      2.130139      2.148307      2.152622   
min        0.399097      0.397988      0.396898      0.395828      0.394177   
25%        1.604720      1.599621      1.595475      1.591735      1.588202   
50%        2.431842      2.422203      2.417037      2.407376      2.399940   
75%        4.506562      4.493653      4.496503      4.497544      4.491808   
max       12.294168     12.283052     12.272669     12.294942     12.283786   

           ...               R714          R715          R716          R717  \
count      ...       23877.000000  23877.000000  23877.000000  23877.000000   
mean       ...           3.117860      3.119370      3.123791      3.129620   
std        ...           1.990339      1.992633      1.993674      1.996469   
min        ...           0.300765      0.303960      0.302355      0.300858   
25%        ...           1.725976      1.729566      1.733253      1.736348   
50%        ...           2.466668      2.468918      2.475062      2.479255   
75%        ...           4.029264      4.023617      4.030480      4.034908   
max        ...          12.926135     12.968840     13.012271     12.941987   

               R718          R719          R720             x             y  \
count  23877.000000  23877.000000  23877.000000  23877.000000  23877.000000   
mean       3.137730      3.141248      3.148506     -0.172472      1.857350   
std        2.007682      2.006146      2.011755      1.986269      2.011609   
min        0.302843      0.304866      0.306926     -3.719565     -2.674327   
25%        1.741396      1.746020      1.750083     -1.872577      0.232127   
50%        2.482881      2.485480      2.492247     -0.041933      1.451492   
75%        4.032610      4.035877      4.043756      1.066181      3.692795   
max       12.873682     12.915410     12.957850      3.985533      5.514922   

              theta  
count  23877.000000  
mean       0.052452  
std        1.843144  
min       -3.141364  
25%       -1.437067  
50%       -0.004991  
75%        1.691020  
max        3.141482  

[8 rows x 724 columns]

In [5]:
get_new_ccs= True
if get_new_ccs:
    
    K_corpus=15
    N=4
    
    kmedias=MiniBatchKMeans(init='k-means++', n_clusters=K_corpus, batch_size=1000,
                      n_init=10, max_no_improvement=10, verbose=0)
    kmedias.fit(lecs)
    ccvk=kmedias.cluster_centers_
    mbk = MiniBatchKMeans(init='k-means++', n_clusters=N, batch_size=1000,
                      n_init=10, max_no_improvement=10, verbose=0)
    mbk.fit(xyth)
    ccxyth=mbk.cluster_centers_
else:
    ccxyth,ccvk=np.load('ccxyth.npy'),np.load('ccvk.npy')
    print("CUANTIZANDO SIN RECALCULAR CC")
aus=[]
auvks=[]
for i,lec in zip(xyth.values, lecs.values):
    _, au= quantized(i , ccxyth)
    aus.append(au)

    auvk= np.power(lec.T-ccvk,2).sum(axis=1,keepdims=True).argmax()
    auvks.append(auvk)
print(i ,au)
data['Y']=aus
data['Vk']=auvks
obs,est= data['Vk'].values,data['Y'].values
data['Y'].describe()   

/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:1279: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:630: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, init_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.p

/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:1328: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, self.batch_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:1328: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, self.batch_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:1328: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, self.batch_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:1328: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, self.batch_size)
/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:1328: DeprecationWarning: This function is deprecated. Please call randint(0, 23876 + 1) instead
  0, n_samples - 1, self.batch_size)
/usr/lib/python2.7/dist-p

(array([-3.05064563,  2.46898844, -1.66027334]), 2)


count    23877.000000
mean         1.547137
std          1.125747
min          0.000000
25%          0.000000
50%          2.000000
75%          3.000000
max          3.000000
Name: Y, dtype: float64

In [6]:
####BAUM WELCH APPROX###############???!?!?!


N=est.max()+1 
K_corpus= obs.max()+1
TRANS=np.zeros((N,N))
for i in range (N):
    fromTO=[]


    indices=np.asarray(np.where(est==i)).ravel()
   

    for indice in indices:

        if (int(indice)==len(est)-1):
            
            indice=indice-1

        fromTO.append(est[indice+1])
    fromTO.append(0)
    fromTO.append(N-1)
    aux=np.asarray(np.bincount(fromTO    ))
    aux[0]=aux[0]-1
    aux[N-1]=aux[N-1]-1
    
    TRANS[i,:]=aux
TRANS=TRANS/TRANS.sum(axis=1)
#####################################3
EMIS= np.zeros((N,K_corpus))
for Vk in range (K_corpus):

    indices=np.asarray(np.where(obs==Vk)).ravel()
    estconvk= est[indices]

    numestenvk=np.bincount(estconvk)
    if (N-len(numestenvk)>0):
        numestenvk=np.append(numestenvk, np.zeros(N-len(numestenvk)))
    EMIS[:,Vk]=(numestenvk/np.bincount(est))

A,B=TRANS,EMIS
PI=np.ones(N)/N
Modelo1=HMM(A,B,PI)
Modelo2= HMM(A,B,PI)
Modelo2.B=B+.0000001
Modelo2.A=A+.0000001





A.shape , EMIS

((4, 4),
 array([[4.77727566e-02, 6.27824403e-02, 5.08392511e-02, 3.58295675e-02,
         3.43124597e-01, 1.68173015e-01, 0.00000000e+00, 4.35765010e-02,
         4.40606843e-02, 1.35571336e-01, 0.00000000e+00, 1.61394448e-04,
         5.95545513e-02, 8.55390575e-03, 0.00000000e+00],
        [3.32120109e-02, 1.59235669e-02, 5.95996360e-02, 1.94040036e-01,
         1.31255687e-01, 5.02729754e-02, 0.00000000e+00, 6.59690628e-02,
         8.21201092e-02, 2.74112830e-01, 3.95814377e-02, 0.00000000e+00,
         4.50409463e-02, 7.27934486e-03, 1.59235669e-03],
        [7.34610123e-02, 2.58549932e-02, 1.46511628e-01, 6.97674419e-02,
         2.40766074e-01, 1.13816689e-01, 0.00000000e+00, 8.82352941e-02,
         5.06155951e-03, 8.65937073e-02, 0.00000000e+00, 1.45006840e-02,
         1.08891929e-01, 2.65389877e-02, 0.00000000e+00],
        [1.50627615e-02, 8.85355649e-02, 6.17573222e-02, 1.64853556e-01,
         2.32803347e-01, 1.45941423e-01, 0.00000000e+00, 2.14225941e-02,
         3.615

In [7]:
def forw_alg(o_k,Modelo):
    PI=Modelo.PI
    K= len(o_k)   #Secuencia Observaciones
    N= len(Modelo.A)  #número de estados
    alpha=np.zeros((N,K))
    alpha[:,0]= PI
    
    for k in range(1,K):
        for j in range (N):
            alpha_k= alpha[:,k-1]
            a= Modelo.A[:,j]
            b= Modelo.B[j,o_k[k]]
            alpha[j,k]=b*np.dot(alpha_k,a)
        #norm=np.linalg.norm(alpha[:,k])
        norm=np.sum(alpha[:,k])
        #alpha[:,k]/= norm
            
                #alpha[k,i]=  np.sum( alpha[:,i-1]*Modelo.A[i,:] *   Modelo.B[:,o_k[k]] )
    
    
    

    
    
    
    
    
    return alpha
def  backw_alg(o_k,Modelo):
    PI=Modelo.PI
    K= len(o_k)   #Secuencia Observaciones
    N= len(Modelo.A)  #número de estados
    beta=np.zeros((N,K))
    beta[:,-1]=1
    
    for t in range(K-1,-1,-1):
        for i in range(N):
            
            beta_t1=beta[:,t+1]
            a= Modelo.A[i,:]
            b= Modelo.B[i,o_k[t]]
            beta[i,t]= b*np.dot(a,beta_t1)
       
        
            

    
    
    
    return beta
    

In [8]:
def forw_alg_norm(o_k,Modelo):
    #MATRIX NOTATION
    PI=Modelo.PI
    K= len(o_k)   #Secuencia Observaciones
    N= len(Modelo.A)  #número de estados
    alpha=np.zeros((N,K))
    c_k= np.zeros(K)
    alpha[:,0]= PI
    c_k[0]=1
    for k in range(1,K):
        alpha_k= alpha[:,k-1]
        a= Modelo.A[:,:]
        b= Modelo.B[:,o_k[k]]
        alpha[:,k]=(b*np.dot(alpha_k,a))* c_k[k-1]
        c_k[k]=1/alpha[:,k].sum()
    return alpha #,c_k
def  backw_alg(o_k,Modelo):
    #MATRIX NOTATION

    PI=Modelo.PI
    K= len(o_k)   #Secuencia Observaciones
    N= len(Modelo.A)  #número de estados
    beta=np.zeros((N,K))
    beta[:,-1]=1
    for t in range(K-2,-1,-1):
        beta_t1=beta[:,t+1]
        beta_t1
        a= Modelo.A[:,:]
        b= Modelo.B[:,o_k[t]]
        beta[:,t]= b*np.dot(a,beta_t1)
    return beta
    

In [9]:
#CALL BAUM WELCH
A,B

(array([[9.93867011e-01, 2.27479527e-04, 3.83036936e-03, 1.50627615e-03],
        [1.61394448e-04, 9.97725205e-01, 9.57592339e-04, 3.34728033e-04],
        [5.97159458e-03, 0.00000000e+00, 9.93844049e-01, 1.33891213e-03],
        [0.00000000e+00, 2.04731574e-03, 1.36798906e-03, 9.96820084e-01]]),
 array([[4.77727566e-02, 6.27824403e-02, 5.08392511e-02, 3.58295675e-02,
         3.43124597e-01, 1.68173015e-01, 0.00000000e+00, 4.35765010e-02,
         4.40606843e-02, 1.35571336e-01, 0.00000000e+00, 1.61394448e-04,
         5.95545513e-02, 8.55390575e-03, 0.00000000e+00],
        [3.32120109e-02, 1.59235669e-02, 5.95996360e-02, 1.94040036e-01,
         1.31255687e-01, 5.02729754e-02, 0.00000000e+00, 6.59690628e-02,
         8.21201092e-02, 2.74112830e-01, 3.95814377e-02, 0.00000000e+00,
         4.50409463e-02, 7.27934486e-03, 1.59235669e-03],
        [7.34610123e-02, 2.58549932e-02, 1.46511628e-01, 6.97674419e-02,
         2.40766074e-01, 1.13816689e-01, 0.00000000e+00, 8.82352941e-02,
  

In [116]:
o_k= obs[:30]
alpha,beta=forw_alg(o_k,Modelo1),backw_alg(o_k,Modelo1)

In [117]:
alpha.shape,beta.shape


((4, 30), (4, 30))

PR(O|Modelo) =  P  ; likelihood Lo(M)

In [118]:
T=len(o_k)
t=len(o_k)-1
P= alpha[:,t].sum()
P

4.3112328732046817e-29

gamma_ij=E{ transitions from state i to j conditioned to O}

In [119]:
gamma=np.zeros((N,N,T))
for t in range(T-1):
    for j in range(N):
        for i in range(N):
            a=Modelo1.A[i,j]
            b=Modelo1.B[j,o_k[t]]
            gamma[i,j,t]=alpha[i,t]*a*b*beta[i,t+1]
gamma=np.sum(gamma,axis=2)/P
gamma

array([[8.15310150e-01, 6.11231373e-05, 2.35294276e-03, 1.11601401e-03],
       [1.07091372e-07, 4.54472653e-04, 1.05009157e-06, 2.99158850e-07],
       [1.02881152e-01, 0.00000000e+00, 2.46842909e+01, 2.86802604e-02],
       [0.00000000e+00, 4.19718257e-04, 6.63001630e-04, 4.59069118e-01]])

gamma_i=E{Num of trans out of gamma_i out of ith state given O} = SUM j gamma_ij

In [120]:
gamma=np.sum(alpha*beta ,axis=1)/P
gamma

array([1.01286739e+00, 1.11603197e-03, 2.55998474e+01, 5.11403678e-01])

In [121]:
A

array([[9.93867011e-01, 2.27479527e-04, 3.83036936e-03, 1.50627615e-03],
       [1.61394448e-04, 9.97725205e-01, 9.57592339e-04, 3.34728033e-04],
       [5.97159458e-03, 0.00000000e+00, 9.93844049e-01, 1.33891213e-03],
       [0.00000000e+00, 2.04731574e-03, 1.36798906e-03, 9.96820084e-01]])

In [178]:
lam=.5
eta=.5
W,V=np.zeros(A.shape),np.zeros(B.shape)
DW,DV=np.zeros(A.shape),np.zeros(B.shape)

In [234]:
A_gd=np.exp(lam*W)
for i in range(N):
    aux=A_gd[i,:].sum()
    A_gd[i,:]=A_gd[i,:]/aux


B_gd= np.exp(lam*V)
for i in range(N):
    aux=B_gd[i,:].sum()
    B_gd[i,:]=B_gd[i,:]/aux


A_gd , B_gd

(array([[0.96561672, 0.01126016, 0.01169299, 0.01143013],
        [0.02195431, 0.93402663, 0.022044  , 0.02197506],
        [0.01450709, 0.01285771, 0.95947918, 0.01315601],
        [0.01140059, 0.01200507, 0.01160734, 0.964987  ]]),
 array([[0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667],
        [0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667],
        [0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667],
        [0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
    

In [235]:
Modelo_gd=HMM(A_gd,B_gd,PI)

In [236]:
o_k= obs[60:90]
alpha,beta=forw_alg(o_k,Modelo_gd),backw_alg(o_k,Modelo_gd)
LoM = alpha[:,-1].sum()

In [237]:
P=LoM
P

7.822642576269835e-35

In [238]:
gamma=np.zeros((N,N,T))
for t in range(T-1):
    for j in range(N):
        for i in range(N):
            a=Modelo1.A[i,j]
            b=Modelo1.B[j,o_k[t]]
            gamma[i,j,t]=alpha[i,t]*a*b*beta[i,t+1]
gamma=np.sum(gamma,axis=2)/P
gamma

array([[1.67815205e+01, 6.75836162e-03, 4.16854360e-02, 2.01827984e-02],
       [1.90785639e-03, 1.96945890e+01, 7.31830995e-03, 3.15799032e-03],
       [9.33045726e-02, 0.00000000e+00, 1.00146115e+01, 1.66199335e-02],
       [0.00000000e+00, 5.96650962e-02, 1.46370942e-02, 1.31332170e+01]])

In [239]:
n_ij_o, n_i_o=gamma , gamma.sum(axis=1)

In [240]:
for i in range (N):
    for j in range (N):
         DW[i,j]=  (eta)* (  n_ij_o[i,j] -(n_i_o[i]* A_gd[i,j]))

In [241]:
DW

array([[ 0.25536834, -0.09148845, -0.0776716 , -0.08620829],
       [-0.21537256,  0.6438756 , -0.21355109, -0.21495194],
       [-0.02678651, -0.06508919,  0.15016498, -0.05828928],
       [-0.07528674, -0.04944608, -0.0693335 ,  0.19406632]])

In [242]:
W=W + DW
W

array([[ 6.90626237, -2.34358761, -2.25433224, -2.30834251],
       [-2.09315415,  6.26717706, -2.0831787 , -2.09084421],
       [-2.01343649, -2.2931269 ,  6.54702077, -2.24045738],
       [-2.32933008, -2.20016028, -2.28743211,  6.81692247]])

1.0

(array([[0.73329418, 0.12383833, 0.05581707, 0.06879585],
        [0.11025501, 0.53650098, 0.06896849, 0.08547578],
        [0.07241293, 0.10008874, 0.8654358 , 0.05559381],
        [0.07859353, 0.11030267, 0.04924024, 0.81690138]]),
 array([[0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667],
        [0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667],
        [0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667],
        [0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
         0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
    

array([[4.86719515, 0.58717424, 0.59375436, 0.58931492],
       [0.73181084, 2.54379677, 0.7336526 , 0.73219758],
       [0.4806364 , 0.47456652, 9.20607736, 0.47622438],
       [0.52165976, 0.52299548, 0.52379327, 6.99769199]])

array([1., 1., 1., 1.])

0.0889894419306184