In [1]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.cluster import  MiniBatchKMeans
import numpy as np
import pandas as pd
from __future__ import division

%autosave 0 

Autosave disabled


In [2]:


class HMM (object):
             def __init__(self,A,B,PI):
                 self.A=A
                 self.B=B
                 self.PI=PI   
def viterbi(obs,Modelo1,PI):
    
    delta=np.zeros((len(obs)+1,len(Modelo1.A)))
    phi=np.zeros((len(obs)+1,len(A)))+666
    path =np.zeros(len(obs)+1)
    T=len(obs)
    Modelo1.PI = PI
    delta[0,:]= Modelo1.PI * Modelo1.B[:,obs[0]]
    phi[0,:]=666
    for t in range(len(obs)):
        for j in range(delta.shape[1]):

            delta [t+1,j]=np.max(delta[t] * A[:,j]) * B[j,obs[t]]
            phi[t+1,j]= np.argmax(delta[t] * A[:,j])
    path[T]=int(np.argmax(delta[T,:]))
    for i in np.arange(T-1,0,-1):
        #print (i,phi[i+1,int(path[i+1])])
        path[i]=phi[i+1,int(path[i+1])]
    return(path)
def cuantizar_xy(xy, cc):
    xycuant=cc
    out=np.power(xycuant-xy,2).sum(axis=1).argmin()
    return out
    
def path_to_xy(path,ccxy):
    estimated= pd.DataFrame(path.astype(int).T)
    estimated.columns=[['Path_vit']]
    estimated['xcuant'] = estimated['Path_vit'].apply(lambda x: ccxy[x,0])
    estimated['ycuant'] = estimated['Path_vit'].apply(lambda x: ccxy[x,1])                                
    return (estimated)
def quantized(xyth,ccxyth):
    xythcuant=np.argmin(np.linalg.norm(xyth-ccxyth,axis=1))
    x,y=ccxyth[xythcuant,:2]
    return ((x,y),(xythcuant))



In [3]:
def Markov_A_2_grafo(A,ccxyth):
    dists=np.zeros(A.shape)
    for i in range(A.shape[0]):
        for j in range (A.shape[1]):
            if A[i,j]!=0 :
                dists[i,j]= np.linalg.norm(ccxyth[i]-ccxyth[j])    
    
    
    con = np.where(dists==0,np.inf,dists)
    graphe2=grafo(ccxyth,con)
    return graphe2


class node(object):
    def __init__(self,x,y):
        self.x=x
        self.y=y
        
        
class grafo (object):
             def __init__(self,nodos,conec):
                 self.nodos=nodos
                 self.conec=conec        

def dijkstra(nodoinicial,nodofinal,graphe):
    

    numnodos= len(graphe.nodos)
    con = graphe.conec
    D= np.ones(numnodos)*np.inf
    Prv= np.ones(numnodos)*np.inf
    V= np.zeros(numnodos)
    a = nodoinicial
    D[a]=0
    Prv[a]=0
    Prv[np.where(con[a]!=np.inf)]=a
    V[a]=1
    Dacc=D[a]
    ########
    D=np.minimum(D,con[a]+D[a])
    cont=0
    sucess=False
    while(sucess==False):
        a = np.argmin(D+np.where (V==1,np.inf, V))
        Dacc=D[a]
        Prv[np.where(D>(con[a]+Dacc) )]=a
        V[a]=1
        D=np.minimum(D,con[a]+Dacc)
        if (a== nodofinal):
            print("RUTA CALCULADA ")
            sucess=True
    rutainv=[]
    rutainv.append(nodofinal)
    while(rutainv[-1]!=nodoinicial):
        prv=Prv[int(rutainv[-1])]
        rutainv.append(prv)

    ruta=[]
    for n in reversed(rutainv):
        ruta.append(n)
    return(ruta)


In [4]:
only_nice=True
data=pd.read_csv('lecturasconodometria_nice.txt')
#data=data.iloc[:5000,:]

cols=['x','y','theta']
n_reads=data.shape[1]-3
n_reads
etiquetas=[]
for i in range (n_reads):
    etiquetas.append('R'+str(i))

        
for lab in cols:
    etiquetas.append(lab)


data.columns=etiquetas

if (only_nice!=True):
    print("NOT ONLY NICE")
    data2=pd.read_csv('lecturasconodometria.txt')
    data2.columns=etiquetas
    data3= pd.concat((data,data2))
    data=data3






####
#index = data[data.y<-1].index
#data=data.drop(index)
data.describe()



#####

xyth=data[['x','y','theta']]

lecs=data.iloc[:,0:n_reads]


data.describe()


R0            R1            R2            R3            R4  \
count  23877.000000  23877.000000  23877.000000  23877.000000  23877.000000   
mean       3.190143      3.189229      3.192182      3.194631      3.196241   
std        2.054171      2.065934      2.079633      2.096674      2.108123   
min        0.406166      0.404345      0.403152      0.401979      0.400827   
25%        1.628477      1.623511      1.618123      1.613172      1.609086   
50%        2.475462      2.465552      2.457282      2.447728      2.441308   
75%        4.466963      4.478095      4.493530      4.490005      4.502109   
max       12.282996     13.500000     12.294272     12.283157     13.500000   

                 R5            R6            R7            R8            R9  \
count  23877.000000  23877.000000  23877.000000  23877.000000  23877.000000   
mean       3.194398      3.190053      3.191011      3.194637      3.191882   
std        2.115277      2.120580      2.130139      2.148307      2.152622   
min        0.399097      0.397988      0.396898      0.395828      0.394177   
25%        1.604720      1.599621      1.595475      1.591735      1.588202   
50%        2.431842      2.422203      2.417037      2.407376      2.399940   
75%        4.506562      4.493653      4.496503      4.497544      4.491808   
max       12.294168     12.283052     12.272669     12.294942     12.283786   

           ...               R714          R715          R716          R717  \
count      ...       23877.000000  23877.000000  23877.000000  23877.000000   
mean       ...           3.117860      3.119370      3.123791      3.129620   
std        ...           1.990339      1.992633      1.993674      1.996469   
min        ...           0.300765      0.303960      0.302355      0.300858   
25%        ...           1.725976      1.729566      1.733253      1.736348   
50%        ...           2.466668      2.468918      2.475062      2.479255   
75%        ...           4.029264      4.023617      4.030480      4.034908   
max        ...          12.926135     12.968840     13.012271     12.941987   

               R718          R719          R720             x             y  \
count  23877.000000  23877.000000  23877.000000  23877.000000  23877.000000   
mean       3.137730      3.141248      3.148506     -0.172472      1.857350   
std        2.007682      2.006146      2.011755      1.986269      2.011609   
min        0.302843      0.304866      0.306926     -3.719565     -2.674327   
25%        1.741396      1.746020      1.750083     -1.872577      0.232127   
50%        2.482881      2.485480      2.492247     -0.041933      1.451492   
75%        4.032610      4.035877      4.043756      1.066181      3.692795   
max       12.873682     12.915410     12.957850      3.985533      5.514922   

              theta  
count  23877.000000  
mean       0.052452  
std        1.843144  
min       -3.141364  
25%       -1.437067  
50%       -0.004991  
75%        1.691020  
max        3.141482  

[8 rows x 724 columns]

In [7]:
get_new_ccs= False
if get_new_ccs:
    
    K_corpus=15
    N=4
    
    kmedias=MiniBatchKMeans(init='k-means++', n_clusters=K_corpus, batch_size=1000,
                      n_init=10, max_no_improvement=10, verbose=0)
    kmedias.fit(lecs)
    ccvk=kmedias.cluster_centers_
    mbk = MiniBatchKMeans(init='k-means++', n_clusters=N, batch_size=1000,
                      n_init=10, max_no_improvement=10, verbose=0)
    mbk.fit(xyth)
    ccxyth=mbk.cluster_centers_
else:
    ccxyth,ccvk=np.load('ccxyth.npy'),np.load('ccvk.npy')
    print("CUANTIZANDO SIN RECALCULAR CC")
aus=[]
auvks=[]
for i,lec in zip(xyth.values, lecs.values):
    _, au= quantized(i , ccxyth)
    aus.append(au)

    auvk= np.power(lec.T-ccvk,2).sum(axis=1,keepdims=True).argmax()
    auvks.append(auvk)
print(i ,au)
data['Y']=aus
data['Vk']=auvks
obs,est= data['Vk'].values,data['Y'].values
data['Y'].describe()   

CUANTIZANDO SIN RECALCULAR CC
(array([-3.05064563,  2.46898844, -1.66027334]), 1)


count    23877.000000
mean         1.300038
std          1.067078
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max          3.000000
Name: Y, dtype: float64

In [15]:
####BAUM WELCH APPROX###############???!?!?!


N=est.max()+1 
K_corpus= obs.max()+1
TRANS=np.zeros((N,N))
for i in range (N):
    fromTO=[]


    indices=np.asarray(np.where(est==i)).ravel()
   

    for indice in indices:

        if (int(indice)==len(est)-1):
            
            indice=indice-1

        fromTO.append(est[indice+1])
    fromTO.append(0)
    fromTO.append(N-1)
    aux=np.asarray(np.bincount(fromTO    ))
    aux[0]=aux[0]-1
    aux[N-1]=aux[N-1]-1
    
    TRANS[i,:]=aux
TRANS=TRANS/TRANS.sum(axis=1)
#####################################3
EMIS= np.zeros((N,K_corpus))
for Vk in range (K_corpus):

    indices=np.asarray(np.where(obs==Vk)).ravel()
    estconvk= est[indices]

    numestenvk=np.bincount(estconvk)
    if (N-len(numestenvk)>0):
        numestenvk=np.append(numestenvk, np.zeros(N-len(numestenvk)))
    EMIS[:,Vk]=(numestenvk/np.bincount(est))

A,B=TRANS,EMIS
PI=np.ones(N)/N
Modelo1=HMM(A,B,PI)
Modelo2= HMM(A,B,PI)
Modelo2.B=B+.0000001
Modelo2.A=A+.0000001





A.shape , EMIS

((4, 4),
 array([[2.93763441e-01, 0.00000000e+00, 3.51254480e-02, 0.00000000e+00,
         1.14121864e-01, 3.06810036e-02, 6.73835125e-03, 5.72043011e-02,
         0.00000000e+00, 1.82939068e-01, 1.62007168e-01, 4.04301075e-02,
         0.00000000e+00, 7.41218638e-02, 2.86738351e-03],
        [4.41809718e-01, 0.00000000e+00, 4.69886529e-02, 0.00000000e+00,
         4.88798371e-02, 6.98283387e-03, 2.24032587e-02, 1.06197265e-01,
         6.98283387e-03, 1.47221414e-01, 3.82601106e-02, 1.55659005e-02,
         0.00000000e+00, 1.15944137e-01, 2.76403841e-03],
        [3.52374514e-01, 0.00000000e+00, 3.29558898e-02, 0.00000000e+00,
         5.64475241e-02, 7.26719621e-03, 3.56599628e-02, 3.48149400e-02,
         0.00000000e+00, 2.51816799e-01, 1.26584418e-01, 1.53794152e-02,
         0.00000000e+00, 8.65303363e-02, 1.69004563e-04],
        [1.99708100e-01, 0.00000000e+00, 2.91899781e-03, 3.45414741e-02,
         1.08489419e-01, 7.29749453e-03, 4.06227195e-02, 1.82194113e-01,
         1.629

In [16]:
def forw_alg(o_k,Modelo):
    PI=Modelo.PI
    K= len(o_k)   #Secuencia Observaciones
    N= len(Modelo.A)  #número de estados
    alpha=np.zeros((N,K))
    alpha[:,0]= PI
    
    for k in range(1,K):
        for j in range (N):
            alpha_k= alpha[:,k-1]
            a= Modelo.A[:,j]
            b= Modelo.B[j,o_k[k]]
            alpha[j,k]=b*np.dot(alpha_k,a)
        #norm=np.linalg.norm(alpha[:,k])
        norm=np.sum(alpha[:,k])
        #alpha[:,k]/= norm
            
                #alpha[k,i]=  np.sum( alpha[:,i-1]*Modelo.A[i,:] *   Modelo.B[:,o_k[k]] )
    
    
    

    
    
    
    
    
    return alpha
def  backw_alg(o_k,Modelo):
    PI=Modelo.PI
    K= len(o_k)   #Secuencia Observaciones
    N= len(Modelo.A)  #número de estados
    beta=np.zeros((N,K))
    beta[:,-1]=1
    
    for t in range(K-1,-1,-1):
        for i in range(N):
            
            beta_t1=beta[:,t+1]
            a= Modelo.A[i,:]
            b= Modelo.B[i,o_k[t]]
            beta[i,t]= b*np.dot(a,beta_t1)
       
        
            

    
    
    
    return beta
    

In [47]:
def forw_alg_norm(o_k,Modelo):
    #MATRIX NOTATION
    PI=Modelo.PI
    K= len(o_k)   #Secuencia Observaciones
    N= len(Modelo.A)  #número de estados
    alpha=np.zeros((N,K))
    c_k= np.zeros(K)
    alpha[:,0]= PI
    c_k[0]=1
    for k in range(1,K):
        alpha_k= alpha[:,k-1]
        a= Modelo.A[:,:]
        b= Modelo.B[:,o_k[k]]
        alpha[:,k]=(b*np.dot(alpha_k,a))* c_k[k-1]
        c_k[k]=1/alpha[:,k].sum()
    return alpha #,c_k
def  backw_alg(o_k,Modelo):
    #MATRIX NOTATION

    PI=Modelo.PI
    K= len(o_k)   #Secuencia Observaciones
    N= len(Modelo.A)  #número de estados
    beta=np.zeros((N,K))
    beta[:,-1]=1
    for t in range(K-2,-1,-1):
        beta_t1=beta[:,t+1]
        beta_t1
        a= Modelo.A[:,:]
        b= Modelo.B[:,o_k[t]]
        beta[:,t]= b*np.dot(a,beta_t1)
    return beta
    

In [11]:
#CALL BAUM WELCH
A,B

(array([[9.94408602e-01, 7.27378528e-04, 5.74615515e-03, 0.00000000e+00],
        [1.29032258e-03, 9.97672389e-01, 0.00000000e+00, 1.70274872e-03],
        [3.58422939e-03, 1.30928135e-03, 9.94253845e-01, 0.00000000e+00],
        [5.73476703e-04, 4.36427117e-04, 0.00000000e+00, 9.98297251e-01]]),
 array([[2.93763441e-01, 0.00000000e+00, 3.51254480e-02, 0.00000000e+00,
         1.14121864e-01, 3.06810036e-02, 6.73835125e-03, 5.72043011e-02,
         0.00000000e+00, 1.82939068e-01, 1.62007168e-01, 4.04301075e-02,
         0.00000000e+00, 7.41218638e-02, 2.86738351e-03],
        [4.41809718e-01, 0.00000000e+00, 4.69886529e-02, 0.00000000e+00,
         4.88798371e-02, 6.98283387e-03, 2.24032587e-02, 1.06197265e-01,
         6.98283387e-03, 1.47221414e-01, 3.82601106e-02, 1.55659005e-02,
         0.00000000e+00, 1.15944137e-01, 2.76403841e-03],
        [3.52374514e-01, 0.00000000e+00, 3.29558898e-02, 0.00000000e+00,
         5.64475241e-02, 7.26719621e-03, 3.56599628e-02, 3.48149400e-02,
  

In [65]:
alpha,beta=forw_alg(o_k,Modelo1),backw_alg(o_k,Modelo1)

In [66]:
alpha.shape,beta.shape


((4, 100), (4, 100))

PR(O|Modelo) =  P

In [73]:
T=len(o_k)
t=len(o_k)-1
P= alpha[:,t].sum()
P

2.7145960573001854e-55

gamma_ij=E{ transitions from state i to j conditioned to O}

In [82]:
gamma=np.zeros((N,N,T))
for t in range(T-1):
    for j in range(N):
        for i in range(N):
            a=Modelo1.A[i,j]
            b=Modelo1.B[j,o_k[t]]
            gamma[i,j,t]=alpha[i,t]*a*b*beta[i,t+1]
gamma=np.sum(gamma,axis=2)/P
gamma

array([[5.67637675e-01, 5.19447075e-04, 3.66086745e-03, 0.00000000e+00],
       [6.86098842e-02, 7.82860889e+01, 0.00000000e+00, 6.70367405e-02],
       [2.04317716e-04, 1.04395127e-04, 6.59923829e-02, 0.00000000e+00],
       [4.24737803e-06, 4.26818294e-06, 0.00000000e+00, 5.06400810e-03]])

gamma_i=E{Num of trans out of gamma_i out of ith state given O} = SUM j gamma_ij

In [69]:
gamma=np.sum(alpha*beta ,axis=1)/P
gamma

array([6.26884827e-01, 7.93109144e+01, 7.88234629e-02, 7.23320952e-03])